"""Use real videos to compose only director work, then reuse a text-only method.

The fixture is generated by rehearsal_r13.py. No commercial model is invoked.
The browser uses the installed package's exact page, not a source-only substitute.
"""
from __future__ import annotations
from copy import deepcopy
from hashlib import sha256
from importlib.resources import files
from pathlib import Path
import argparse
import json
import shutil
import subprocess
import zipfile

import manju
from manju.authoring.core import canonical, digest, file_digest
from manju.authoring.flexibility import CreativeTemplate, compose_archives, compose_studios, difference, read_verified
from manju.authoring.studio import verify_studio
from playwright.sync_api import sync_playwright, expect


def main():
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('fixture',type=Path);p.add_argument('output',type=Path)
    args=p.parse_args();fixture=args.fixture.resolve();root=args.output.resolve();root.mkdir(parents=True,exist_ok=False)
    donor=fixture/'STUDIO.zip';other=fixture/'另一候选_合成.mp4'
    donor_doc,_=read_verified(donor)
    original_files={x.name:file_digest(x) for x in fixture.iterdir() if x.is_file()}
    html=Path(str(files('manju.authoring').joinpath('data/workbench.html')))
    requests=[];errors=[];contexts=[];downloads=[]
    with sync_playwright() as pw:
        browser=pw.chromium.launch(executable_path=shutil.which('chromium'),headless=True,args=['--no-sandbox'])
        def fresh():
            ctx=browser.new_context(accept_downloads=True,viewport={'width':1365,'height':980});contexts.append(ctx)
            page=ctx.new_page();page.set_default_timeout(15000)
            page.on('pageerror',lambda e:errors.append(str(e)))
            page.on('request',lambda r:requests.append(r.url))
            page.set_content(html.read_text(encoding='utf-8'),wait_until='load')
            return page
        def save(page,button,name):
            with page.expect_download() as item:page.locator(button).click()
            path=root/name;item.value.save_as(path);downloads.append({'path':name,'suggested_name':item.value.suggested_filename,'sha256':file_digest(path)})
            return path
        def apply_preview(page):
            expect(page.locator('#flex-preview')).to_be_visible()
            page.locator('#flex-confirmed').check();page.locator('#flex-apply').click()
            expect(page.locator('#flex-status')).to_contain_text('变更完成')
        page=fresh()
        page.locator('#shot-id').fill('新镜头_A_不覆盖')
        page.locator('#task').select_option('edit');page.locator('#duration').fill('3')
        page.locator('#prompt').fill('  保留当前新稿\n 只从旧方案拿导演材料 ')
        page.locator('#asset-role').select_option('source_video');page.locator('#asset-files').set_input_files(other)
        page.wait_for_function('()=>ManjuWorkbench.state.assets.length===1&&!ManjuWorkbench.state.busy')
        page.locator('#repair-source').set_input_files(other)
        page.wait_for_function('()=>ManjuRepair.state.source!==null&&!ManjuRepair.state.busy')
        page.locator('#repair-change').fill('  当前返工方案，不能被旧方案覆盖 ')
        page.locator('#director-change').fill('当前的临时导演说明')
        before=page.evaluate('ManjuStudio.view()')
        page.locator('#flex-branch-name').fill('A方案_我的新镜头')
        a=save(page,'#flex-save-branch','A_STUDIO.zip')
        assert verify_studio(a)['media_files']==1
        page.locator('#verify-studio-download').set_input_files(a)
        expect(page.locator('#studio-save-status')).to_contain_text('与当前三个工作区一致')
        assert not page.evaluate('ManjuStudio.needsBackup()')
        page.locator('#flex-donor-file').set_input_files(donor)
        expect(page.locator('#flex-preview-compose')).to_be_enabled()
        assert before==page.evaluate('ManjuStudio.view()')
        page.locator('#flex-take-director').check();page.locator('#flex-preview-compose').click()
        expect(page.locator('#flex-preview')).to_be_visible()
        assert before==page.evaluate('ManjuStudio.view()')
        page.set_viewport_size({'width':390,'height':844})
        assert page.evaluate('document.documentElement.scrollWidth<=innerWidth')
        page.locator('#flex-section').screenshot(path=str(root/'selective-preview-narrow.png'))
        report=page.evaluate('ManjuFlex.state.pending.report')
        expected=compose_studios(read_verified(a)[0],donor_doc,['director'])
        assert report==difference(read_verified(a)[0],expected)
        (root/'COMPOSITION_PREVIEW.json').write_bytes(canonical(report))
        apply_preview(page)
        after=page.evaluate('ManjuStudio.view()')
        assert after['workspace']==before['workspace'] and after['repair']==before['repair']
        assert after['auxiliary_form']==before['auxiliary_form']
        assert after['director']==donor_doc.model_dump(mode='json')['director']
        assert page.locator('#quality-only').is_checked()
        assert page.evaluate('ManjuStudio.needsBackup()')
        assert page.evaluate('ManjuDirector.state.anchors[0].guide.width')==1920
        for selector in ['#director-video','#repair-video']:
            page.locator(selector).evaluate('v=>v.play()')
            page.wait_for_function('s=>document.querySelector(s).currentTime>0.2',arg=selector)
            page.locator(selector).evaluate('v=>v.pause()')
        page.locator('#flex-branch-name').fill('B方案_只拿导演材料')
        b=save(page,'#flex-save-branch','B_COMPOSED_STUDIO.zip');b_doc,b_receipt=read_verified(b)
        assert b_receipt['media_files']==5
        assert b_receipt['studio_sha256']==report['after_sha256']==digest(expected)
        # CLI constructs a portable sibling; restore the result with the old
        # strict Studio reader. The original A and donor ZIPs are unchanged.
        cli_path=root/'B_CLI_COMPOSED.zip'
        cli=compose_archives(a,donor,['director'],cli_path)
        assert cli['media_files']==5
        assert b_doc.director.model_dump(mode='json')==expected.director.model_dump(mode='json')
        page.locator('#flex-undo-confirmed').check();page.locator('#flex-undo').click()
        expect(page.locator('#flex-status')).to_contain_text('已撤回')
        assert page.evaluate('ManjuStudio.view()')==before
        assert not page.evaluate('ManjuStudio.needsBackup()')
        page.close();page=fresh()
        page.locator('#import-studio').set_input_files(b)
        expect(page.locator('#studio-restore-preview')).to_be_visible()
        page.locator('#studio-restore-confirmed').check();page.locator('#apply-studio').click()
        expect(page.locator('#studio-save-status')).to_contain_text('三个工作区已从实际核验')
        assert page.evaluate('ManjuStudio.view()')==after
        for selector in ['#director-video','#repair-video']:
            page.locator(selector).evaluate('v=>v.play()')
            page.wait_for_function('s=>document.querySelector(s).currentTime>0.2',arg=selector)
            page.locator(selector).evaluate('v=>v.pause()')
        b2=save(page,'#export-studio','B_REOPENED.zip')
        assert b2.read_bytes()==b.read_bytes()
        page.locator('#flex-template-box > summary').click()
        page.locator('#flex-template-name').fill('我的连续镜头方法')
        page.locator('#flex-template-notes').fill('先确定运动，再设计外观。只复用要求，不复用旧批准。')
        template_file=save(page,'#flex-export-template','PERSONAL_TEMPLATE.json')
        template=CreativeTemplate.model_validate_json(template_file.read_bytes())
        assert not template.contains_approvals and not template.contains_media
        page.locator('#director-change').fill('新的外观修改')
        page.locator('#flex-template-file').set_input_files(template_file)
        expect(page.locator('#flex-preview-template')).to_be_enabled()
        page.locator('#flex-template-mode').select_option('fill_empty');page.locator('#flex-preview-template').click()
        apply_preview(page)
        assert page.locator('#director-change').input_value()=='新的外观修改'
        page.locator('#flex-template-mode').select_option('replace');page.locator('#flex-preview-template').click()
        apply_preview(page)
        assert page.locator('#director-change').input_value()==template.fields['director']['director-change']
        page.set_viewport_size({'width':390,'height':844})
        assert page.evaluate('document.documentElement.scrollWidth<=innerWidth')
        page.locator('#flex-section').screenshot(path=str(root/'template-narrow.png'))
        page.locator('#flex-branch-name').fill('C方案_个人模板')
        c=save(page,'#flex-save-branch','C_TEMPLATE_STUDIO.zip')
        c_doc,c_receipt=read_verified(c)
        assert c_receipt['ok']
        assert c_doc.workspace.draft.form['shot-id']=='新镜头_A_不覆盖'
        assert c_doc.director.source.sha256==b_doc.director.source.sha256
        with zipfile.ZipFile(b) as archive:
            for binding in b_doc.media:
                assert sha256(archive.read('media/'+binding.sha256)).hexdigest()==binding.sha256
        assert original_files=={x.name:file_digest(x) for x in fixture.iterdir() if x.is_file()}
        external=[u for u in requests if u.startswith(('http:','https:'))]
        assert not external and not errors,(external,errors)
        result={'ok':True,'package_import':str(Path(manju.__file__).resolve()),'version':manju.__version__,
            'html_sha256':file_digest(html),'actual_browser_downloads':downloads,
            'source_archives_unchanged':True,'unselected_workspaces_unchanged':True,
            'native_1920x1080_guide_unchanged':True,'restored_videos_played_without_rebinding':True,
            'composition_report_python_browser_equal':True,'preview_after_hash_matches_saved_document':True,'old_studio_reader_verified_new_output':True,
            'reopened_reexport_byte_identical':True,'one_step_undo_restored_verified_A':True,
            'template_fill_empty_and_replace_exercised':True,'current_quality_only':page.locator('#quality-only').is_checked(),
            'current_confirmations_restored':False,'commercial_generation_calls':0,
            'browser_version':browser.version,'transport':'isolated_document',
            'native_file_navigation_certified':False,'http_requests':len(external),'page_errors':errors,
            'B_studio_verification':b_receipt,'CLI_composition':cli,'C_studio_verification':c_receipt}
        (root/'RESULT.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
        for context in contexts:context.close()
        browser.close()
    print(json.dumps(result,ensure_ascii=False,indent=2))


if __name__=='__main__':main()
