// Pure shared story operations. Only explicitly scoped source text enters context.
const STORY_FORMS={undecided:'先决定作品形态，不套用固定镜长、集数或付费卡点。',film:'围绕单片的核心冲突与结束条件组织场景，不要求可无限续集。',limited_series:'围绕跨集因果与明确收束组织；不以能否续写一百集作门槛。',ongoing_series:'检查能持续产生故事的关系与压力，同时保留每集造成的后果。',vertical_serial:'可使用短剧方法，但集数、镜长和付费结构均由你另行决定。',music_visual:'以实际音乐、动作与视觉组织为主，不强制三幕或人物成长。',custom:'按自定创作意图组织，不继承其他体裁的硬限制。'};
const STORY_KINDS={character:'人物',relationship:'关系',setting:'设定',fact:'事实 / 伏笔',consequence:'跨场后果'};
const STORY_ROLES={identity:'身份',space:'空间与路线',performance:'表演与动作',camera:'机位与运镜',voice:'声音参考',music:'音乐与拍点',look:'外观与光线',other:'其他'};
const STORY_KEYS=['schema_id','project_id','title','form','intent','ending','sources','scenes','briefs','link'];
const STORY_SCENE_KEYS=['id','episode','title','purpose','action','dialogue','before','after','source_ids','references','policy'];
const STORY_SOURCE_KEYS=['id','kind','name','text','scope','from_scene_id','knower_id','provenance'];
const STORY_CONTENT_KEYS=['schema_id','project_id','project_title','form','intent','ending','scene','order_prefix','history_omitted','history','sources','withheld','policy','automatic_execution','creative_approval'];
function storyDigest(x){const s=new SHA256();s.update(encoder.encode(canonical(x)));return s.hex();}
function storyText(x,max,label){require(typeof x==='string'&&[...x].length<=max&&!/[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/u.test(x),label+' 超长或文本无效');}
function storyId(x){require(typeof x==='string'&&/^[A-Za-z][A-Za-z0-9_-]{0,79}$/.test(x),'故事稳定编号无效');}
function storyPolicy(p){exactKeys(p,['scope','character_id','history_count'],'上下文策略');require(['author','audience','character'].includes(p.scope),'上下文范围无效');if(p.character_id!==null)storyId(p.character_id);integer(p.history_count,0,20,'前情场数');}
function storySource(s){exactKeys(s,STORY_SOURCE_KEYS,'故事依据');storyId(s.id);require(Object.hasOwn(STORY_KINDS,s.kind),'依据类型无效');storyText(s.name,240,'名称');storyText(s.text,12000,'依据正文');storyText(s.provenance,2000,'来源');require(['author','audience','character'].includes(s.scope),'知情范围无效');if(s.from_scene_id!==null)storyId(s.from_scene_id);if(s.knower_id!==null)storyId(s.knower_id);}
function storyScene(s){exactKeys(s,STORY_SCENE_KEYS,'场景');storyId(s.id);for(const[k,max]of Object.entries({episode:120,title:240,purpose:4000,action:12000,dialogue:12000,before:4000,after:4000}))storyText(s[k],max,'场景 '+k);require(Array.isArray(s.source_ids)&&s.source_ids.length<=64&&new Set(s.source_ids).size===s.source_ids.length,'本场引用重复或超限');s.source_ids.forEach(storyId);require(Array.isArray(s.references)&&s.references.length<=32,'参考职责超限');const ids=new Set();for(const r of s.references){exactKeys(r,['id','sha256','bytes','filename','role','inherit','exclude','time_range'],'参考职责');storyId(r.id);require(!ids.has(r.id),'参考编号重复');ids.add(r.id);require(hashPattern.test(r.sha256),'参考哈希无效');integer(r.bytes,1,MAX_FILE,'参考字节');storyText(r.filename,240,'参考文件名');require(r.filename.length>0&&Object.hasOwn(STORY_ROLES,r.role),'参考文件名或职责无效');storyText(r.inherit,4000,'继承内容');storyText(r.exclude,4000,'禁止继承');storyText(r.time_range,500,'时间说明');}storyPolicy(s.policy);}
function storyCompiled(c){
 exactKeys(c,STORY_CONTENT_KEYS,'简报内容');require(c.schema_id==='manju.story-brief/v1'&&c.automatic_execution===false&&c.creative_approval===false,'简报人工边界无效');storyId(c.project_id);storyText(c.project_title,240,'简报作品名');require(Object.hasOwn(STORY_FORMS,c.form),'简报作品形态无效');storyText(c.intent,12000,'作品意图');if(c.ending!==null)storyText(c.ending,12000,'作者结束条件');storyScene(c.scene);storyPolicy(c.policy);integer(c.history_omitted,0,512,'省略前情场数');
 require(Array.isArray(c.sources)&&c.sources.length<=64,'简报依据超限');c.sources.forEach(storySource);require(Array.isArray(c.order_prefix)&&c.order_prefix.length>0&&c.order_prefix.length<=512&&Array.isArray(c.history)&&c.history.length<=20&&Array.isArray(c.withheld)&&c.withheld.length<=64,'简报前情格式无效');c.order_prefix.forEach(storyId);require(new Set(c.order_prefix).size===c.order_prefix.length&&c.order_prefix.at(-1)===c.scene.id,'简报顺序无效');
 for(const h of c.history){exactKeys(h,['id','episode','title','action','dialogue','after'],'前情');storyId(h.id);for(const[k,max]of [['episode',120],['title',240],['action',12000],['dialogue',12000],['after',4000]])storyText(h[k],max,'前情 '+k);}
 for(const w of c.withheld){exactKeys(w,['id','reason'],'省略依据');storyId(w.id);require(['future','outside_scope'].includes(w.reason),'省略原因无效');}
 require(c.history_omitted+c.history.length===c.order_prefix.length-1,'省略场数与实际顺序不符');const expected=c.history.length?c.order_prefix.slice(-1-c.history.length,-1):[];require(canonical(c.history.map(h=>h.id))===canonical(expected),'前情不是实际先前顺序');
 require(c.policy.scope==='character'?c.policy.character_id!==null&&c.history.length===0:c.policy.character_id===null,'知情范围无效');require(c.policy.scope==='author'||c.ending===null,'非作者上下文不能携带作者结束条件');const claimed=[...c.sources,...c.withheld].map(x=>x.id);require(new Set(claimed).size===claimed.length&&canonical([...claimed].sort())===canonical([...c.scene.source_ids].sort()),'简报引用覆盖不完整');
 for(const x of c.sources){if(c.policy.scope==='author')continue;require(x.from_scene_id===null||c.order_prefix.includes(x.from_scene_id),'未来依据不能进入范围');require(x.scope==='audience'||c.policy.scope==='character'&&x.scope==='character'&&x.knower_id===c.policy.character_id,'引用超出此次阅读范围');}
}
function storyNormalize(value){
 exactKeys(value,STORY_KEYS,'故事工作本');require(value.schema_id==='manju.story-notebook/v1','故事格式不受支持');storyId(value.project_id);storyText(value.title,240,'作品名');require(Object.hasOwn(STORY_FORMS,value.form),'作品形态无效');storyText(value.intent,12000,'作品意图');storyText(value.ending,12000,'结束条件');
 for(const[key,max]of [['sources',512],['scenes',512],['briefs',128]])require(Array.isArray(value[key])&&value[key].length<=max&&new Set(value[key].map(s=>s.id)).size===value[key].length,key+' 编号重复或数量超限');
 const entities=new Map(value.sources.map(s=>[s.id,s])),scenes=new Set(value.scenes.map(s=>s.id)),characters=new Set(value.sources.filter(s=>s.kind==='character').map(s=>s.id));
 for(const s of value.sources){storySource(s);require(s.from_scene_id===null||scenes.has(s.from_scene_id),'依据指向不存在的场景');require(s.scope==='character'?characters.has(s.knower_id):s.knower_id===null,'知情记录必须明确关联人物');}
 for(const s of value.scenes){storyScene(s);require(s.source_ids.every(id=>entities.has(id)),'场景引用缺失依据');require(s.policy.scope==='character'?characters.has(s.policy.character_id):s.policy.character_id===null,'场景视角必须明确指定人物');}
 for(const b of value.briefs){exactKeys(b,['id','scene_id','content','content_sha256','observation'],'制作简报版本');storyId(b.id);storyId(b.scene_id);exactKeys(b.content,STORY_CONTENT_KEYS,'简报内容');const c=b.content;storyCompiled(c);require(c.scene.id===b.scene_id&&hashPattern.test(b.content_sha256)&&storyDigest(c)===b.content_sha256,'简报内容与固定哈希不符');const o=b.observation;exactKeys(o,['candidate_sha256','candidate_bytes','seen','heard','deviation','layer'],'实际复盘');require((o.candidate_sha256===null)===(o.candidate_bytes===null),'复盘素材身份不完整');if(o.candidate_sha256!==null){require(hashPattern.test(o.candidate_sha256),'复盘哈希无效');integer(o.candidate_bytes,1,MAX_FILE,'复盘素材字节');}for(const k of ['seen','heard','deviation'])storyText(o[k],8000,'复盘 '+k);require(['unreviewed','story','references','space','performance','camera','sound','edit','none_observed'].includes(o.layer),'返工层无效');}
 if(value.link!==null){exactKeys(value.link,['brief_id','shot_id','prompt_sha256'],'当前镜头关联');require(value.briefs.some(b=>b.id===value.link.brief_id)&&typeof value.link.shot_id==='string'&&hashPattern.test(value.link.prompt_sha256),'镜头关联无效');}
 require(encoder.encode(canonical(value)).length<=1024*1024,'故事工作本超过 1 MiB，请分卷保留原文件');return clone(value);
}
function storyCompile(doc,sceneId,override=null){
 const order=doc.scenes.map(s=>s.id),index=order.indexOf(sceneId);require(index>=0,'场景已不存在，请保留旧简报并手动复核');const scene=doc.scenes[index],policy=override||scene.policy,byId=new Map(doc.sources.map(s=>[s.id,s])),sources=[],withheld=[];
 for(const id of scene.source_ids){const s=byId.get(id);require(s,'场景引用缺失依据');const future=s.from_scene_id!==null&&order.indexOf(s.from_scene_id)>index,allowed=policy.scope==='author'||(!future&&(s.scope==='audience'||policy.scope==='character'&&s.scope==='character'&&s.knower_id===policy.character_id));if(allowed)sources.push(clone(s));else withheld.push({id,reason:future?'future':'outside_scope'});}
 const previous=doc.scenes.slice(Math.max(0,index-policy.history_count),index),history=policy.scope==='character'?[]:previous.map(s=>({id:s.id,episode:s.episode,title:s.title,action:s.action,dialogue:s.dialogue,after:s.after}));
 return {schema_id:'manju.story-brief/v1',project_id:doc.project_id,project_title:doc.title,form:doc.form,intent:doc.intent,ending:policy.scope==='author'?doc.ending:null,scene:clone(scene),order_prefix:order.slice(0,index+1),history_omitted:index-history.length,history,sources,withheld,policy:clone(policy),automatic_execution:false,creative_approval:false};
}
function storyBriefStatus(doc,b){let current;try{current=storyCompile(doc,b.scene_id,b.content.policy);}catch(e){return{id:b.id,status:'needs_review',changes:['scene_missing'],detail:e.message};}const changes=STORY_CONTENT_KEYS.filter(k=>canonical(current[k])!==canonical(b.content[k]));return{id:b.id,status:changes.length?'needs_review':'current',changes,recorded_sha256:b.content_sha256,current_sha256:storyDigest(current),meaning_verified:false,creative_approval:false};}
function storyPrompt(c){const s=c.scene;let rows=[`【作品】${c.project_title} · ${c.form}`,STORY_FORMS[c.form],c.intent,`【本场】${s.episode} ${s.title}`,`场景作用：${s.purpose}`,`入场状态：${s.before}`,`动作与因果：\n${s.action}`,`对白 / 画内文字（保留原语言）：\n${s.dialogue}`,`离场变化：${s.after}`];if(c.ending!==null)rows.push('【作者结束条件，可能剧透】\n'+c.ending);rows.push(`前情省略：${c.history_omitted} 场（人物视角不自动继承他处发生的事情）`);for(const h of c.history)rows.push(`【已发生前情 ${h.episode} ${h.title}】\n${h.action}\n${h.dialogue}\n留下变化：${h.after}`);for(const x of c.sources)rows.push(`【引用 ${STORY_KINDS[x.kind]}：${x.name}】\n${x.text}`);for(const r of s.references)rows.push(`【参考 ${r.id}：${STORY_ROLES[r.role]}】\n文件 SHA-256：${r.sha256}\n负责：${r.inherit}\n禁止继承：${r.exclude}\n时间说明：${r.time_range}`);rows.push('【边界】只使用以上明确提供的资料。未公开资料已省略；未知不要编造。实际模型模式与输入支持仍须单独核对。');return rows.filter(x=>x!=='').join('\n\n');}
