// Optional, live-updated story working copy. Saved in Desk/v2 only when present.
const storyState={doc:null,sceneId:null,sourceId:null,pending:null,linkPending:null,tab:'scenes'};
const storyNewId=prefix=>prefix+'_'+Array.from(crypto.getRandomValues(new Uint8Array(12)),n=>n.toString(16).padStart(2,'0')).join('');
function storyView(){return storyState.doc===null?null:clone(storyState.doc);}
function storyCurrent(){return storyState.doc?.scenes.find(s=>s.id===storyState.sceneId)||null;}
function storySelectedSource(){return storyState.doc?.sources.find(s=>s.id===storyState.sourceId)||null;}
function storyNotice(text,error=false){$('story-status').textContent=text;$('story-status').classList.toggle('error',error);}
function storySafety(){if(storyState.doc?.link){const b=storyState.doc.briefs.find(x=>x.id===storyState.doc.link.brief_id);if(b&&storyBriefStatus(storyState.doc,b).status!=='current'){invalidate();storyNotice('已关联简报的上游内容或场序改变。旧文件保留，请复核并建立新版本；没有自动重生成。',true);}}}
function storyChanged(){window.ManjuStoryDiff?.clear('story-import-diff');storyState.pending=null;storyState.linkPending=null;$('story-import-preview').hidden=true;$('story-link-preview').hidden=true;$('story-link-confirmed').checked=false;$('story-import-confirmed').checked=false;storySafety();window.ManjuDesk?.changed();$('story-unlink').disabled=!storyState.doc?.link;storyUpdateBadges();}
function storyUpdateBadges(){const d=storyState.doc;$('story-count').textContent=d?`${d.scenes.length} 场 · ${d.sources.length} 份依据 · ${d.briefs.filter(b=>storyBriefStatus(d,b).status!=='current').length} 份待复核`:'可选，不改变原有工作方式';}
function storyTab(tab){storyState.tab=tab;for(const x of ['scenes','sources','briefs']){$('story-tab-'+x).hidden=x!==tab;document.querySelector(`[data-story-tab="${x}"]`).setAttribute('aria-pressed',String(x===tab));}if(tab==='briefs')storyRenderBriefs();}
function storyOptions(select,items,value,blank='未指定'){select.replaceChildren();if(blank!==null){const o=element('option',blank);o.value='';select.append(o);}for(const[id,label]of items){const o=element('option',label);o.value=id;select.append(o);}select.value=value||'';}
function storyCharacters(){return (storyState.doc?.sources||[]).filter(x=>x.kind==='character').map(x=>[x.id,x.name||'未命名人物']);}
function storyRenderLists(){const d=storyState.doc;$('story-scenes').replaceChildren();$('story-sources').replaceChildren();if(!d)return;for(const[s,i]of d.scenes.map((s,i)=>[s,i])){const b=element('button',`${i+1}. ${s.episode} ${s.title||'未命名场景'}`);b.setAttribute('aria-current',String(s.id===storyState.sceneId));b.addEventListener('click',()=>{storyState.sceneId=s.id;storyRenderLists();storyRenderScene();});$('story-scenes').append(b);}for(const s of d.sources){const b=element('button',`${STORY_KINDS[s.kind]} · ${s.name||'未命名'}`);b.setAttribute('aria-current',String(s.id===storyState.sourceId));b.addEventListener('click',()=>{storyState.sourceId=s.id;storyRenderLists();storyRenderSource();});$('story-sources').append(b);}}
function storyRenderScene(){const s=storyCurrent();$('story-scene-editor').hidden=!s;if(!s)return;for(const[k,id]of Object.entries({episode:'story-episode',title:'story-scene-title',purpose:'story-purpose',action:'story-action',dialogue:'story-dialogue',before:'story-before',after:'story-after'}))$(id).value=s[k];$('story-scene-id').textContent='稳定编号 '+s.id;$('story-scope').value=s.policy.scope;$('story-history').value=s.policy.history_count;storyOptions($('story-character'),storyCharacters(),s.policy.character_id);$('story-character').disabled=s.policy.scope!=='character';const i=storyState.doc.scenes.indexOf(s);$('story-move-up').disabled=i===0;$('story-move-down').disabled=i===storyState.doc.scenes.length-1;storyRenderPicks();storyRefreshMedia();storyRenderReferences();}
function storyRenderPicks(){const s=storyCurrent(),list=$('story-source-picks');list.replaceChildren();if(!s)return;if(!storyState.doc.sources.length){list.append(element('p','先到「人物与依据」添加，也可以先写场景。','hint'));return;}for(const x of storyState.doc.sources){const l=element('label',undefined,'checkline'),c=document.createElement('input');c.type='checkbox';c.checked=s.source_ids.includes(x.id);c.addEventListener('change',()=>{if(c.checked){if(s.source_ids.length>=64){c.checked=false;storyNotice('每场最多引用64项，当前其他文字保持。',true);return;}s.source_ids.push(x.id);}else s.source_ids=s.source_ids.filter(id=>id!==x.id);storyChanged();});l.append(c,document.createTextNode(`${STORY_KINDS[x.kind]} · ${x.name||'未命名'} · ${x.scope==='author'?'仅作者':x.scope==='audience'?'公开':'人物知情'}`));list.append(l);}}
function storyRenderSource(){const s=storySelectedSource();$('story-source-editor').hidden=!s;if(!s)return;for(const[k,id]of Object.entries({kind:'story-source-kind',name:'story-source-name',text:'story-source-text',scope:'story-source-scope',provenance:'story-source-provenance'}))$(id).value=s[k];storyOptions($('story-source-knower'),storyCharacters(),s.knower_id);$('story-source-knower').disabled=s.scope!=='character';storyOptions($('story-source-from'),storyState.doc.scenes.map((x,i)=>[x.id,`${i+1}. ${x.episode} ${x.title||'未命名'}`]),s.from_scene_id,'自故事开始已知（由我声明）');}
function storyRefreshMedia(){const items=[...studioBindings()].map(([h,e])=>[h,e.file.name+' · '+h.slice(0,10)]);storyOptions($('story-reference-file'),items,$('story-reference-file').value,'选择已经绑定的原文件');}
function storyRenderReferences(){const s=storyCurrent(),list=$('story-references');list.replaceChildren();if(!s)return;for(const r of s.references){const box=element('div',undefined,'story-reference');box.append(element('strong',`${STORY_ROLES[r.role]} · ${r.filename}`),element('p',`${r.sha256.slice(0,14)} · ${studioBindings().has(r.sha256)?'当前文件已绑定':'原文件当前缺失，请重新绑定后外发'}`,'small'));for(const[k,label,max]of [['inherit','这一份负责什么',4000],['exclude','哪些内容禁止继承',4000],['time_range','生效范围 / 已确认的拍点（文字说明，不是接口参数）',500]]){const l=element('label',label,'field'),input=document.createElement('textarea');input.maxLength=max;input.value=r[k];input.addEventListener('input',()=>{r[k]=input.value;storyChanged();});l.append(input);box.append(l);}const b=element('button','移除此职责（不删原文件）');b.addEventListener('click',()=>{s.references=s.references.filter(x=>x.id!==r.id);storyChanged();storyRenderReferences();});box.append(b);list.append(box);}}
function storyRender(){const d=storyState.doc;$('story-editor').hidden=!d;$('story-home-warning').hidden=!d;$('story-create').disabled=Boolean(d);$('story-export').disabled=!d;$('story-unlink').disabled=!d?.link;if(d){$('story-title').value=d.title;$('story-form').value=d.form;$('story-intent').value=d.intent;$('story-ending').value=d.ending;$('story-route').textContent=STORY_FORMS[d.form];if(!d.scenes.some(s=>s.id===storyState.sceneId))storyState.sceneId=d.scenes[0]?.id||null;if(!d.sources.some(s=>s.id===storyState.sourceId))storyState.sourceId=d.sources[0]?.id||null;storyRenderLists();storyRenderScene();storyRenderSource();storyRenderBriefs();}storyUpdateBadges();storyTab(storyState.tab);}
function storyInstall(doc){storyState.doc=doc===null?null:storyNormalize(doc);storyState.sceneId=null;storyState.sourceId=null;storyState.pending=null;storyState.linkPending=null;$('story-import-preview').hidden=true;$('story-link-preview').hidden=true;$('story-import-confirmed').checked=false;$('story-link-confirmed').checked=false;storyRender();}
function storyAssertRequest(){const d=storyState.doc,l=d?.link;if(!l)return;require($('shot-id').value===l.shot_id,'故事关联对应另一镜头，请重新带入或明确解除关联');const b=d.briefs.find(x=>x.id===l.brief_id);require(b&&storyBriefStatus(d,b).status==='current','故事依据已变，请先到「版本与复盘」复核并建立新简报，或明确解除关联');for(const r of b.content.scene.references)require(state.assets.some(a=>a.sha256===r.sha256&&a.bytes===r.bytes)&&state.files.has(r.sha256),'简报参考尚未绑定到当前镜头素材区：'+r.filename+'；其他区有文件不等于本次模型已收到');require(storyDigest($('prompt').value)===l.prompt_sha256,'关联后的提示词被手动修改，请重新带入故事版本或明确解除关联；文字未删除');}
function storyHandler(fn){return handled(async e=>{try{return await fn(e);}catch(x){storyNotice('未完成：'+x.message,true);throw x;}finally{window.ManjuDesk?.changed();}});}
$('story-create').addEventListener('click',()=>{if(storyState.doc)return;storyInstall({schema_id:'manju.story-notebook/v1',project_id:storyNewId('project'),title:'',form:'undecided',intent:'',ending:'',sources:[],scenes:[],briefs:[],link:null});storyChanged();storyNotice('已建立空白故事工作本。未完成的内容也会随收工包保存。');});
for(const k of ['title','intent','ending'])$('story-'+k).addEventListener('input',()=>{if(!storyState.doc)return;storyState.doc[k]=$('story-'+k).value;storyChanged();});
$('story-form').addEventListener('change',()=>{if(!storyState.doc)return;storyState.doc.form=$('story-form').value;$('story-route').textContent=STORY_FORMS[storyState.doc.form];storyChanged();});
for(const b of document.querySelectorAll('[data-story-tab]'))b.addEventListener('click',()=>storyTab(b.dataset.storyTab));
$('story-add-scene').addEventListener('click',storyHandler(()=>{const d=storyState.doc;require(d&&d.scenes.length<512,'每份工作本最多512场');const s={id:storyNewId('scene'),episode:'',title:'',purpose:'',action:'',dialogue:'',before:'',after:'',source_ids:[],references:[],policy:{scope:'audience',character_id:null,history_count:0}};d.scenes.push(s);storyState.sceneId=s.id;storyChanged();storyRenderLists();storyRenderScene();$('story-scene-title').focus();}));
for(const[k,id]of Object.entries({episode:'story-episode',title:'story-scene-title',purpose:'story-purpose',action:'story-action',dialogue:'story-dialogue',before:'story-before',after:'story-after'}))$(id).addEventListener('input',()=>{const s=storyCurrent();if(s){s[k]=$(id).value;storyChanged();if(['episode','title'].includes(k))storyRenderLists();}});
for(const[id,offset]of [['story-move-up',-1],['story-move-down',1]])$(id).addEventListener('click',()=>{const d=storyState.doc,s=storyCurrent();if(!d||!s)return;const i=d.scenes.indexOf(s),j=i+offset;if(j<0||j>=d.scenes.length)return;[d.scenes[i],d.scenes[j]]=[d.scenes[j],d.scenes[i]];storyChanged();storyRenderLists();storyRenderScene();storyRenderSource();storyNotice('按实际场序重新计算上下文；旧简报保持，可在版本区查看影响。');});
$('story-scope').addEventListener('change',storyHandler(()=>{const s=storyCurrent();if(!s)return;const scope=$('story-scope').value;if(scope==='character'&&!storyCharacters().length){$('story-scope').value=s.policy.scope;throw new Error('先建立至少一名人物，再选择人物视角');}s.policy.scope=scope;s.policy.character_id=scope==='character'?storyCharacters()[0][0]:null;storyChanged();storyRenderScene();}));
$('story-character').addEventListener('change',()=>{const s=storyCurrent();if(s&&s.policy.scope==='character'){if(!$('story-character').value){$('story-character').value=s.policy.character_id;return;}s.policy.character_id=$('story-character').value;storyChanged();}});
$('story-history').addEventListener('change',storyHandler(()=>{const n=Number($('story-history').value);if($('story-history').value===''||!Number.isInteger(n)||n<0||n>20){$('story-history').value=storyCurrent().policy.history_count;throw new Error('前情场数须为0至20的整数；已保留上次有效值');}storyCurrent().policy.history_count=n;storyChanged();}));
$('story-add-source').addEventListener('click',storyHandler(()=>{const d=storyState.doc;require(d&&d.sources.length<512,'每份工作本最多512项依据');const s={id:storyNewId('source'),kind:'character',name:'',text:'',scope:'author',from_scene_id:null,knower_id:null,provenance:''};d.sources.push(s);storyState.sourceId=s.id;storyChanged();storyRenderLists();storyRenderSource();storyRenderPicks();$('story-source-name').focus();}));
for(const[k,id]of Object.entries({name:'story-source-name',text:'story-source-text',provenance:'story-source-provenance'}))$(id).addEventListener('input',()=>{const s=storySelectedSource();if(s){s[k]=$(id).value;storyChanged();if(k==='name')storyRenderLists();}});
$('story-source-kind').addEventListener('change',storyHandler(()=>{const d=storyState.doc,s=storySelectedSource(),kind=$('story-source-kind').value;if(!s)return;try{require(kind==='character'||!d.sources.some(x=>x.knower_id===s.id)&&!d.scenes.some(x=>x.policy.character_id===s.id),'这名人物正在被知情范围引用，请先改关联');s.kind=kind;storyChanged();storyRenderLists();storyRenderSource();}catch(e){$('story-source-kind').value=s.kind;throw e;}}));
$('story-source-scope').addEventListener('change',storyHandler(()=>{const s=storySelectedSource();if(!s)return;const scope=$('story-source-scope').value;try{require(scope!=='character'||storyCharacters().length,'先建立人物再设置知情范围');s.scope=scope;s.knower_id=scope==='character'?storyCharacters()[0][0]:null;storyChanged();storyRenderSource();}catch(e){$('story-source-scope').value=s.scope;throw e;}}));
$('story-source-knower').addEventListener('change',()=>{const s=storySelectedSource();if(s&&s.scope==='character'){if(!$('story-source-knower').value){$('story-source-knower').value=s.knower_id;return;}s.knower_id=$('story-source-knower').value;storyChanged();}});
$('story-source-from').addEventListener('change',()=>{const s=storySelectedSource();if(s){s.from_scene_id=$('story-source-from').value||null;storyChanged();}});
$('story-refresh-media').addEventListener('click',()=>{storyRefreshMedia();storyRenderReferences();});
$('story-add-reference').addEventListener('click',storyHandler(()=>{const s=storyCurrent(),h=$('story-reference-file').value,entry=studioBindings().get(h);require(s&&entry,'选择已绑定的原素材');require(s.references.length<32,'每场最多32份职责记录');s.references.push({id:storyNewId('ref'),sha256:h,bytes:entry.file.size,filename:entry.file.name,role:$('story-reference-role').value,inherit:'',exclude:'',time_range:''});storyChanged();storyRenderReferences();}));
$('story-freeze').addEventListener('click',storyHandler(()=>{const d=storyNormalize(storyState.doc),s=storyCurrent();require(s,'先建立并选择场景');require(d.form!=='undecided','先明确作品形态，不替你选择创作框架');require(s.action.trim()||s.dialogue.trim(),'至少记录本场动作或对白；空白草稿仍可收工保存');require(d.briefs.length<128,'每份工作本最多128份简报，请另存后分卷');const c=storyCompile(d,s.id),b={id:storyNewId('brief'),scene_id:s.id,content:c,content_sha256:storyDigest(c),observation:{candidate_sha256:null,candidate_bytes:null,seen:'',heard:'',deviation:'',layer:'unreviewed'}};const next=clone(d);next.briefs.push(b);storyState.doc=storyNormalize(next);storyChanged();storyTab('briefs');storyNotice('本场版本已记录。内容检查不等于创作批准；旧版本未覆盖。');}));
function storyBriefPreview(b){const d=storyState.doc;require(storyBriefStatus(d,b).status==='current','该版本的上游已变，请复核并记录新版本');const prompt=storyPrompt(b.content);require([...prompt].length<=16000,'合成提示词过长，请减少本场引用或前情后建立新版本');storyState.linkPending={briefId:b.id,guard:deskGuard(),prompt};$('story-old-prompt').value=$('prompt').value;$('story-new-prompt').value=prompt;$('story-link-confirmed').checked=false;$('story-link-apply').disabled=true;$('story-link-preview').hidden=false;$('story-link-preview').scrollIntoView({block:'center'});}
function storyMarkdown(b){return '# '+(b.content.scene.title||'场景制作简报')+'\n\n版本：'+b.id+'\n内容 SHA-256：'+b.content_sha256+'\n\n'+storyPrompt(b.content)+'\n\n原简报不可就地改写。这个包不是整个工程备份；不授权生成、付款、审片或选片。\n';}
async function storyExportBrief(b){const d=storyState.doc;require(storyBriefStatus(d,b).status==='current','旧简报上游已变。请先复核并记录新版本；完整故事JSON仍保留旧版');const guard=deskGuard(),entries=[],inventory={},all=studioBindings(),seen=new Set();for(const r of b.content.scene.references){if(seen.has(r.sha256))continue;const e=all.get(r.sha256);require(e&&e.file.size===r.bytes,'参考原文件未绑定：'+r.filename);const checked=await inspectFile(e.file);require(checked.sha256===r.sha256,'参考实际内容已变');const ext=/\.(png|jpe?g|webp|mp4|mov|m4v|wav|mp3|m4a|flac|ogg)$/i.exec(e.file.name)?.[0].toLowerCase()||'.bin',name='media/'+r.sha256+ext;entries.push({name,data:e.file,crc:checked.crc});inventory[name]=r.sha256;seen.add(r.sha256);}for(const[name,value]of [['BRIEF.json',b],['README.md',storyMarkdown(b)]]){const data=typeof value==='string'?encoder.encode(value):jsonBytes(value);entries.push({name,data,crc:crc32(data)});inventory[name]=await hash(data);}const data=jsonBytes({schema_id:'manju.story-brief-manifest/v1',files:inventory});entries.push({name:'MANIFEST.json',data,crc:crc32(data)});require(guard===deskGuard(),'导出期间故事或素材改变，没有发出旧版本');download(zipStore(entries),'STORY_BRIEF_'+b.content_sha256.slice(0,12)+'.zip');storyNotice('已发起简报与实际参考下载，不是整工程备份，也没有执行生成。');}
function storyRenderBriefs(){const list=$('story-briefs');list.replaceChildren();const d=storyState.doc;if(!d)return;if(!d.briefs.length){list.append(element('p','在场景区记录一个制作版本，就能看到内容与引用变化。','empty'));return;}for(const b of [...d.briefs].reverse()){const report=storyBriefStatus(d,b),box=element('article',undefined,'story-brief');box.dataset.stale=String(report.status!=='current');box.append(element('h3',`${b.content.scene.episode} ${b.content.scene.title||'未命名场景'}`),element('p',report.status==='current'?'● 引用内容与当前一致 · 未进行语义或画质验收':'● 需要复核：'+report.changes.join('、'),report.status==='current'?'bound':'reason'),element('p',b.id+' · '+b.content_sha256.slice(0,16),'small muted'));const actions=element('div',undefined,'actions');for(const[label,fn]of [['预览带入当前镜头',()=>storyBriefPreview(b)],['下载简报与参考 ZIP',()=>storyExportBrief(b)]]){const button=element('button',label);button.disabled=report.status!=='current';button.addEventListener('click',storyHandler(fn));actions.append(button);}box.append(actions);const detail=element('details'),summary=element('summary','查看固定内容（不会随上游自动改写）');detail.append(summary,element('pre',storyPrompt(b.content)));box.append(detail);const review=element('details'),rt=element('summary','实际成片复盘（人工记录，不是自动批准）');review.append(rt);const picker=element('select'),l=element('label','关联实际候选文件','field');const videos=[...studioBindings()].filter(([,e])=>VIDEO_EXTS.includes(extension(e.file.name))).map(([h,e])=>[h,e.file.name]);if(b.observation.candidate_sha256&&!videos.some(([h])=>h===b.observation.candidate_sha256))videos.push([b.observation.candidate_sha256,'已记录哈希，当前未绑定']);storyOptions(picker,videos,b.observation.candidate_sha256,'尚未关联实际候选');picker.addEventListener('change',()=>{const e=studioBindings().get(picker.value);b.observation.candidate_sha256=e?picker.value:null;b.observation.candidate_bytes=e?e.file.size:null;storyChanged();});l.append(picker);review.append(l);for(const[k,label]of [['seen','画面实际发生了什么'],['heard','实际听见什么（未听清就留空）'],['deviation','与原计划的偏差 / 时间位置']]){const field=element('label',label,'field'),input=document.createElement('textarea');input.value=b.observation[k];input.maxLength=8000;input.addEventListener('input',()=>{b.observation[k]=input.value;storyChanged();});field.append(input);review.append(field);}const layer=element('select');storyOptions(layer,[['unreviewed','尚未复核'],['story','剧情因果'],['references','身份 / 参考职责'],['space','空间 / 预演'],['performance','动作 / 表演'],['camera','镜头'],['sound','声音'],['edit','剪辑'],['none_observed','人工未观察到偏差（不是自动批准）']],b.observation.layer,null);layer.addEventListener('change',()=>{b.observation.layer=layer.value;storyChanged();});review.append(layer,element('p','只改变复盘记录，不改原故事、不调用模型、不改变原审片或选片状态。','hint'));box.append(review);list.append(box);}}
$('story-link-confirmed').addEventListener('change',()=>{$('story-link-apply').disabled=!storyState.linkPending||!$('story-link-confirmed').checked;});
$('story-link-cancel').addEventListener('click',()=>{storyState.linkPending=null;$('story-link-preview').hidden=true;});
$('story-link-apply').addEventListener('click',storyHandler(()=>{const p=storyState.linkPending;require(p&&$('story-link-confirmed').checked&&p.guard===deskGuard(),'请重新预览并确认；旧预览不能覆盖新输入');const b=storyState.doc.briefs.find(x=>x.id===p.briefId);require(b&&storyBriefStatus(storyState.doc,b).status==='current','简报已过时');$('shot-id').value=b.scene_id;$('prompt').value=p.prompt;state.stage='draft';state.draftHash=null;invalidate();storyState.doc.link={brief_id:b.id,shot_id:b.scene_id,prompt_sha256:storyDigest(p.prompt)};storyChanged();storyNotice('已明确带入并关联。旧批准已清除，质量优先开启；继续按具体型号核对。');$('quality-only').checked=true;window.ManjuExperience?.reveal('prompt',{focus:true});}));
$('story-unlink').addEventListener('click',()=>{if(!storyState.doc?.link)return;if(!confirm('解除故事版本关联？镜头文字仍保留，但此后不再阻止它沿用过期故事依据。'))return;storyState.doc.link=null;invalidate();storyChanged();storyNotice('已解除显式关联。镜头文字保留，没有重新批准。');});
$('story-export').addEventListener('click',storyHandler(()=>{const d=storyNormalize(storyState.doc);download(new Blob([jsonBytes(d)],{type:'application/json'}),'STORY_'+d.project_id+'.json');storyNotice('已发起完整故事JSON下载，包含未完成文字、旧简报和复盘；不含媒体原文件。');}));
$('story-file').addEventListener('change',storyHandler(async e=>{try{const f=e.target.files[0];if(!f)return;storyState.pending=null;$('story-import-preview').hidden=true;window.ManjuStoryDiff?.clear('story-import-diff');require(f.size<=2*1024*1024,'故事JSON不得超过2MiB');const guard=deskGuard(),doc=storyNormalize(strictJSON(new TextDecoder('utf-8',{fatal:true}).decode(await f.arrayBuffer())));require(guard===deskGuard(),'读取期间工作已变，未覆盖新内容');window.ManjuStoryDiff?.present('story-import-diff',storyView(),doc);storyState.pending={doc,guard};$('story-import-summary').textContent=`将替换故事工作本：${doc.title||'未命名'}，${doc.scenes.length} 场，${doc.sources.length} 项依据，${doc.briefs.length} 份简报。当前镜头与原素材不变；关联确认清除。请先保存需要保留的旧工作。`;$('story-import-confirmed').checked=false;$('story-import-apply').disabled=true;$('story-import-preview').hidden=false;}finally{e.target.value='';}}));
$('story-import-confirmed').addEventListener('change',()=>{$('story-import-apply').disabled=!storyState.pending||!$('story-import-confirmed').checked;});
$('story-import-apply').addEventListener('click',storyHandler(()=>{const p=storyState.pending;require(p&&$('story-import-confirmed').checked&&p.guard===deskGuard(),'导入预览已变，请重新打开');const doc=clone(p.doc);doc.link=null;storyInstall(doc);invalidate();storyChanged();storyNotice('故事已恢复；当前镜头未替换，需重新明确关联。');}));
$('story-import-cancel').addEventListener('click',()=>{storyState.pending=null;$('story-import-preview').hidden=true;});
for(const type of ['input','change'])document.addEventListener(type,e=>{if(e.target.closest('#story-link-preview,#story-import-preview'))return;queueMicrotask(()=>{if(storyState.pending&&storyState.pending.guard!==deskGuard()){window.ManjuStoryDiff?.clear('story-import-diff','对照已过期，请重新打开。');storyState.pending=null;$('story-import-apply').disabled=true;$('story-import-summary').textContent='预览后内容已变。未覆盖新输入，请重新打开。';}if(storyState.linkPending&&storyState.linkPending.guard!==deskGuard()){storyState.linkPending=null;$('story-link-apply').disabled=true;storyNotice('带入预览已过时，未覆盖新输入。',true);}});});
window.ManjuStory={view:storyView,install:storyInstall,normalize:storyNormalize,compile:storyCompile,status:storyBriefStatus,prompt:storyPrompt,digest:storyDigest,assertRequest:storyAssertRequest,render:storyRender,state:storyState};
