// Local review records are declarations, not identity signatures or automatic edits.
const reviewState={document:null,files:new Map(),pending:[],urls:[],reveal:false,busy:false,revision:0,formRevision:0,dirty:false};
const CRITERIA=['identity','motion','camera','continuity','audio','artifacts','prompt_adherence'];
const VERDICTS={approve_draft:'批准草稿',revise:'需要修改',reject:'拒绝候选'};
const clone=value=>JSON.parse(JSON.stringify(value));
const bodyWithout=(value,key)=>Object.fromEntries(Object.entries(value).filter(([k])=>k!==key));
function reviewStatus(text,error=false){$('review-status').textContent=text;$('review-status').style.color=error?'var(--red)':'';status(text,error);}
function reviewChanged(){reviewState.revision++;reviewState.dirty=true;state.dirty=true;}
function reviewJsonBytes(doc){const data=jsonBytes(doc);require(data.length<=2*1024*1024,'审片记录超过 2 MiB，请另建新场次，旧记录仍可保留');return data;}
function candidateValue(c){onlyKeys(c,['sha256','bytes','filename','duration_ms','width','height','media_check'],'候选');require(hashPattern.test(c.sha256),'候选哈希无效');safePath(c.filename);require(!c.filename.includes('/')&&VIDEO_EXTS.includes(extension(c.filename)),'候选必须使用视频文件名');const result={sha256:c.sha256,bytes:integer(c.bytes,1,2*1024*1024*1024,'候选大小'),filename:string(c.filename,240,'文件名',1),duration_ms:c.duration_ms==null?null:integer(c.duration_ms,1,86400000,'视频时长'),width:c.width==null?null:integer(c.width,1,32768,'视频宽度'),height:c.height==null?null:integer(c.height,1,32768,'视频高度'),media_check:c.media_check||'hash_only'};require(['hash_only','browser_metadata','ffprobe'].includes(result.media_check),'未知视频检查方式');require(result.media_check==='hash_only'||[result.duration_ms,result.width,result.height].every(x=>x!==null),'已测量视频缺少元数据');return result;}
async function normalizeReview(input){
 onlyKeys(input,['schema_id','session','decisions'],'审片文档');require(input.schema_id==='manju.review-document/v1','未知审片文档');const s=input.session;onlyKeys(s,['schema_id','request','request_sha256','candidates','nonce','blind_order','session_sha256','no_automatic_selection'],'审片场次');require(s.schema_id==='manju.review-session/v1'&&s.no_automatic_selection===true,'场次版本或人工边界不正确');const request=normalizeRequest(s.request);require(request.stage==='draft'&&await hash(request)===s.request_sha256,'草稿任务或哈希不一致');require(Array.isArray(s.candidates)&&s.candidates.length>=1&&s.candidates.length<=12,'候选数量无效');const candidates=s.candidates.map(candidateValue),hashes=candidates.map(c=>c.sha256);require(new Set(hashes).size===hashes.length,'同样的视频内容不能算作两个候选');require(/^[a-f0-9]{32}$/.test(s.nonce),'场次随机种子不正确');const keyed=await Promise.all(hashes.map(async h=>[await hash({nonce:s.nonce,sha256:h}),h]));keyed.sort((a,b)=>a[0]<b[0]?-1:a[0]>b[0]?1:a[1]<b[1]?-1:1);require(canonical(keyed.map(v=>v[1]))===canonical(s.blind_order),'候选标签顺序不一致');const session={schema_id:s.schema_id,request,request_sha256:s.request_sha256,candidates,nonce:s.nonce,blind_order:s.blind_order,no_automatic_selection:true};require(await hash(session)===s.session_sha256,'审片场次内容已改变');session.session_sha256=s.session_sha256;
 require(Array.isArray(input.decisions)&&input.decisions.length<=1000,'审片历史格式或数量无效');const decisions=[];let previous=null;
 for(const d of input.decisions){onlyKeys(d,['schema_id','session_sha256','request_sha256','candidate_sha256','sequence','previous_decision_sha256','verdict','reviewer','notes','criteria','declared_at','human_declared','picture_lock_authorized','decision_sha256'],'人工决定');require(d.schema_id==='manju.review-decision/v1'&&d.human_declared===true&&d.picture_lock_authorized===false,'决定不符合人工边界');require(d.sequence===decisions.length+1&&d.previous_decision_sha256===previous&&d.session_sha256===session.session_sha256&&d.request_sha256===session.request_sha256&&hashes.includes(d.candidate_sha256),'决定顺序、前驱或候选不匹配');require(Object.hasOwn(VERDICTS,d.verdict),'未知决定');const criteria=d.criteria||{};onlyKeys(criteria,CRITERIA,'人工评分');for(const v of Object.values(criteria))if(v!==null)integer(v,1,5,'人工评分');require(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/.test(d.declared_at)&&!isNaN(Date.parse(d.declared_at))&&new Date(d.declared_at).toISOString().replace('.000','')===d.declared_at,'决定时间无效');const decision={schema_id:d.schema_id,session_sha256:d.session_sha256,request_sha256:d.request_sha256,candidate_sha256:d.candidate_sha256,sequence:d.sequence,previous_decision_sha256:d.previous_decision_sha256,verdict:d.verdict,reviewer:string(d.reviewer,120,'审片人',1),notes:string(d.notes,6000,'审片说明',1),criteria,declared_at:d.declared_at,human_declared:true,picture_lock_authorized:false};require(await hash(decision)===d.decision_sha256,'人工决定内容已改变');decision.decision_sha256=d.decision_sha256;decisions.push(decision);previous=d.decision_sha256;}
 const document={schema_id:'manju.review-document/v1',session,decisions};reviewJsonBytes(document);return document;
}
async function newReview(request,candidates,nonce){request=normalizeRequest(request);require(request.stage==='draft','请使用草稿任务建立新场次');if(!nonce){const values=new Uint8Array(16);globalThis.crypto.getRandomValues(values);nonce=Array.from(values,b=>b.toString(16).padStart(2,'0')).join('');}const cs=candidates.map(candidateValue),pairs=await Promise.all(cs.map(async c=>[await hash({nonce,sha256:c.sha256}),c.sha256]));pairs.sort((a,b)=>a[0]<b[0]?-1:a[0]>b[0]?1:a[1]<b[1]?-1:1);const session={schema_id:'manju.review-session/v1',request,request_sha256:await hash(request),candidates:cs,nonce,blind_order:pairs.map(p=>p[1]),no_automatic_selection:true};session.session_sha256=await hash(session);return normalizeReview({schema_id:'manju.review-document/v1',session,decisions:[]});}
function latestReview(doc,h){return [...doc.decisions].reverse().find(d=>d.candidate_sha256===h)||null;}
function sameCreativeIntent(request,original){const allowed=['stage','approved_draft_sha256','resolution'];return canonical(Object.fromEntries(Object.entries(request).filter(([k])=>!allowed.includes(k))))===canonical(Object.fromEntries(Object.entries(original).filter(([k])=>!allowed.includes(k))));}
async function measuredCandidate(file,entry){return new Promise((resolve,reject)=>{const video=document.createElement('video'),url=URL.createObjectURL(file);let done=false;const finish=(error,result)=>{if(done)return;done=true;clearTimeout(timer);video.removeAttribute('src');video.load();URL.revokeObjectURL(url);error?reject(new Error(error)):resolve(result);};const timer=setTimeout(()=>finish('读取视频元数据超时，请检查本地编码或使用 CLI 的显式 hash-only 模式'),10000);video.preload='metadata';video.onloadedmetadata=()=>{try{finish(null,candidateValue({sha256:entry.sha256,bytes:file.size,filename:file.name,duration_ms:Math.round(video.duration*1000),width:video.videoWidth,height:video.videoHeight,media_check:'browser_metadata'}));}catch(e){finish(e.message);}};video.onerror=()=>finish('浏览器不能解码这个候选，请使用本地播放器检查并通过 CLI 建立记录');video.src=url;});}
async function addReviewFiles(files){require(!reviewState.busy,'候选仍在处理中');reviewState.busy=true;try{const added=[],bindings=new Map(reviewState.files);for(const file of files){require(VIDEO_EXTS.includes(extension(file.name)),'请选择支持的视频文件扩展名');reviewStatus('正在核对实际候选：'+file.name);const entry=await inspectFile(file);const known=reviewState.document?.session.candidates.find(c=>c.sha256===entry.sha256);if(reviewState.document){require(known,'这个视频不属于当前固定场次；请另建场次，不要改写已审片名单');require(known.bytes===file.size,'候选大小不符');}else{require(!reviewState.pending.concat(added).some(c=>c.sha256===entry.sha256),'相同视频内容已经添加，不重复计数');added.push(await measuredCandidate(file,entry));require(reviewState.pending.length+added.length<=8,'浏览器最多比较 8 个候选');}bindings.set(entry.sha256,entry);const sizes=new Map([...state.files,...bindings]);require([...sizes.values()].reduce((n,e)=>n+e.file.size,0)<=MAX_TOTAL,'当前素材和候选总量超过浏览器本地 512 MiB 限制');}reviewState.files=bindings;reviewState.pending.push(...added);reviewChanged();renderReview();reviewStatus('候选文件已核对；没有改写磁盘原视频。');}finally{reviewState.busy=false;$('review-files').value='';}}
function renderReview(){for(const url of reviewState.urls)URL.revokeObjectURL(url);reviewState.urls=[];const grid=$('candidate-grid'),select=$('review-candidate'),chosen=select.value;grid.replaceChildren();select.replaceChildren(new Option('请明确选择',''));const doc=reviewState.document,cs=doc?doc.session.blind_order.map(h=>doc.session.candidates.find(c=>c.sha256===h)):reviewState.pending;cs.forEach((c,i)=>{const label=doc?'候选 '+String.fromCharCode(65+i):'待建场次 '+(i+1),card=element('div',undefined,'candidate-card');card.append(element('h3',label));if(reviewState.reveal)card.append(element('div',c.filename,'hint'));const bound=reviewState.files.get(c.sha256);if(bound){const video=element('video');video.controls=true;video.preload='metadata';video.muted=true;video.playsInline=true;const url=URL.createObjectURL(bound.file);reviewState.urls.push(url);video.src=url;video.addEventListener('volumechange',()=>{if(!video.muted&&video.volume>0)grid.querySelectorAll('video').forEach(v=>{if(v!==video)v.muted=true;});});card.append(video);}else card.append(element('div','尚未绑定实际视频，请重新选择原文件。','empty'));card.append(element('div',`${c.duration_ms===null?'未测量':(c.duration_ms/1000)+' 秒'} · ${c.width||'?'} × ${c.height||'?'} · ${(c.bytes/1024/1024).toFixed(2)} MiB`,'hint'));card.append(element('code',c.sha256));const d=doc?latestReview(doc,c.sha256):null;card.append(element('p',d?VERDICTS[d.verdict]+' · '+d.notes:'尚未评审','hint'));grid.append(card);if(doc)select.append(new Option(label,c.sha256));});if(!cs.length)grid.append(element('div','请先添加实际视频。','empty'));if([...select.options].some(o=>o.value===chosen))select.value=chosen;$('review-history').textContent=doc?JSON.stringify({session_sha256:doc.session.session_sha256,request_sha256:doc.session.request_sha256,candidates:doc.session.candidates.length,decisions:doc.decisions},null,2):'还没有审片记录。';$('reveal-review').textContent=reviewState.reveal?'隐藏文件名':'揭示文件名';$('create-review').textContent=doc?'另建审片场次（先保存）':'按当前草稿建立审片场次';}
async function boundCandidate(doc,h){const c=doc.session.candidates.find(c=>c.sha256===h);require(c,'请明确选择本场次的候选');const bound=reviewState.files.get(h);require(bound,'请重新绑定已评审的实际视频文件');const entry=await inspectFile(bound.file);require(entry.sha256===h&&entry.file.size===c.bytes,'实际视频与审片记录不一致');return {candidate:c,entry};}
async function appendReviewDecision(){require(!reviewState.busy,'审片操作仍在处理中');reviewState.busy=true;const revision=reviewState.revision,formRevision=reviewState.formRevision;try{require(reviewState.document,'请先建立或导入审片场次');require($('review-confirmed').checked,'请先明确确认已查看实际视频');const doc=await normalizeReview(clone(reviewState.document)),h=$('review-candidate').value;const verdict=$('review-verdict').value;require(Object.hasOwn(VERDICTS,verdict),'请明确选择决定');const reviewer=string($('review-human').value,120,'审片人',1),notes=string($('review-notes').value,6000,'说明',1),score=$('review-score').value;await boundCandidate(doc,h);const body={schema_id:'manju.review-decision/v1',session_sha256:doc.session.session_sha256,request_sha256:doc.session.request_sha256,candidate_sha256:h,sequence:doc.decisions.length+1,previous_decision_sha256:doc.decisions.at(-1)?.decision_sha256||null,verdict,reviewer,notes,criteria:score?{prompt_adherence:Number(score)}:{},declared_at:new Date().toISOString().slice(0,19)+'Z',human_declared:true,picture_lock_authorized:false};body.decision_sha256=await hash(body);doc.decisions.push(body);const valid=await normalizeReview(doc);require(revision===reviewState.revision&&formRevision===reviewState.formRevision,'场次或表单在记录期间变化，未写入旧决定');reviewState.document=valid;reviewChanged();$('review-confirmed').checked=false;$('promotion-confirmed').checked=false;renderReview();reviewStatus('已追加第 '+valid.decisions.length+' 条决定。请保存审片 JSON；没有自动选片。');}finally{reviewState.busy=false;}}
async function promotionProof(request){require(reviewState.document,'定稿包必须导入真实审片记录，不能仅填写草稿哈希');const revision=reviewState.revision,doc=await normalizeReview(clone(reviewState.document));require(request.stage==='final'&&sameCreativeIntent(request,doc.session.request),'创作意图、时长、画幅或素材已改变，请重新审片');const decision=latestReview(doc,request.approved_draft_sha256);require(decision?.verdict==='approve_draft','该候选在本记录中的最新决定不是批准草稿');const {candidate,entry}=await boundCandidate(doc,request.approved_draft_sha256);require(revision===reviewState.revision,'审片记录在封包期间变化');return {document:doc,candidate,entry,revision};}
async function promoteReview(){require(!reviewState.busy,'审片操作仍在处理中');require($('promotion-confirmed').checked,'请明确确认定稿晋升');require(reviewState.document,'先建立审片场次');const current=getRequest(),h=$('review-candidate').value;require(sameCreativeIntent(current,reviewState.document.session.request),'当前任务已变更，不能套用旧场次批准');const revision=state.revision;const request=clone(reviewState.document.session.request);request.stage='final';request.approved_draft_sha256=h;if($('promotion-resolution').value.trim())request.resolution=$('promotion-resolution').value.trim();const valid=normalizeRequest(request);await promotionProof(valid);require(revision===state.revision,'任务在核对期间变化，未进行晋升');fillRequest(valid);invalidate();$('promotion-confirmed').checked=false;reviewStatus('已建立绑定实际草稿的定稿任务。回到步骤 03 检查适配，再导出含视频与审片证据的 ZIP。');}
function reviewReport(doc){const rows=['# Manju 候选审片记录','',`镜头：${doc.session.request.shot_id}`,`场次：${doc.session.session_sha256}`,'','不自动选片，不批准影片锁定；本地声明不是身份签名。隐藏文件名不构成科学双盲。',''];doc.session.blind_order.forEach((h,i)=>{const c=doc.session.candidates.find(c=>c.sha256===h),d=latestReview(doc,h);rows.push('## 候选 '+String.fromCharCode(65+i),'SHA-256：'+h,'文件：'+(reviewState.reveal?c.filename:'未揭示来源'),'最新决定：'+(d?VERDICTS[d.verdict]:'尚未评审'));if(d)rows.push('审片人：'+d.reviewer,d.notes,'人工评分（不自动排名）：'+JSON.stringify(d.criteria));rows.push('');});rows.push('历史决定数：'+doc.decisions.length,'完整可复核历史见一起导出的审片 JSON。','');return rows.join('\n');}
$('open-review').addEventListener('click',()=>{$('review-section').scrollIntoView({behavior:'smooth',block:'start'});});
$('review-files').addEventListener('change',handled(()=>addReviewFiles([...$('review-files').files])));
$('create-review').addEventListener('click',handled(async()=>{require(!reviewState.busy,'候选仍在处理中');if(reviewState.document){require(confirm('新建场次会清空当前页面的审片记录与候选绑定。请先导出旧记录，磁盘文件不会改变。'),'保留原场次');reviewState.document=null;reviewState.pending=[];reviewState.files.clear();reviewState.reveal=false;reviewChanged();renderReview();reviewStatus('已清空当前场次，请添加新候选。');return;}require(reviewState.pending.length,'先添加至少一个候选');const revision=state.revision,rrevision=reviewState.revision,doc=await newReview(getRequest(),reviewState.pending);require(revision===state.revision&&rrevision===reviewState.revision,'任务或候选在建立期间发生变化');reviewState.document=doc;reviewState.pending=[];reviewState.reveal=false;reviewChanged();renderReview();reviewStatus('已固定任务和候选名单。请逐一看片并作出人工决定。');}));
$('reveal-review').addEventListener('click',()=>{reviewState.reveal=!reviewState.reveal;renderReview();});
$('record-review').addEventListener('click',handled(appendReviewDecision));
$('promote-review').addEventListener('click',handled(promoteReview));
$('export-review').addEventListener('click',handled(async()=>{require(reviewState.document,'尚无审片场次');const doc=await normalizeReview(clone(reviewState.document));download(new Blob([reviewJsonBytes(doc)],{type:'application/json'}),'MANJU_REVIEW_'+doc.session.session_sha256.slice(0,12)+'_r'+doc.decisions.length+'.json');reviewState.dirty=false;reviewStatus('已触发审片 JSON 下载，请确认已保存。视频仍需单独保留，最终定稿包会复制选中的批准视频。');}));
$('export-review-report').addEventListener('click',handled(async()=>{require(reviewState.document,'尚无审片场次');const doc=await normalizeReview(clone(reviewState.document));download(new Blob([reviewReport(doc)],{type:'text/markdown;charset=utf-8'}),'MANJU_REVIEW_REPORT_r'+doc.decisions.length+'.md');reviewStatus('已触发报告下载。请同时保存完整审片 JSON，Markdown 不是机器可验证记录。');}));
$('import-review').addEventListener('change',handled(async()=>{require(!reviewState.busy,'候选仍在处理中');const file=$('import-review').files[0];if(!file)return;require(file.size<=2*1024*1024,'审片 JSON 超过 2 MiB');const doc=await normalizeReview(JSON.parse(await file.text()));if(reviewState.document||reviewState.pending.length)require(confirm('用导入的审片场次替换当前页面记录？请先保存现有记录。磁盘原文件不会改变。'),'保留当前记录');reviewState.document=doc;reviewState.pending=[];reviewState.files.clear();reviewState.reveal=false;reviewChanged();renderReview();$('import-review').value='';reviewStatus('记录已验证，实际视频尚未绑定。当前镜头任务没有被覆盖。');}));
$('load-review-request').addEventListener('click',handled(async()=>{require(reviewState.document,'尚无审片场次');require(confirm('用此场次的草稿任务替换上方当前任务？请先保存当前草稿。不会改动磁盘工程。'),'保留当前任务');fillRequest(clone(reviewState.document.session.request));state.sourceContext=null;showContext();invalidate();reviewStatus('已载入场次草稿，原素材需要按内容哈希重新绑定。');}));
$('play-review').addEventListener('click',handled(async()=>{const videos=[...$('candidate-grid').querySelectorAll('video')];require(videos.length,'尚无已绑定视频');videos.forEach(v=>{v.pause();v.currentTime=0;});const results=await Promise.allSettled(videos.map(v=>v.play()));require(results.every(r=>r.status==='fulfilled'),'至少一个候选无法播放，请单独检查');}));
$('pause-review').addEventListener('click',()=>{$('candidate-grid').querySelectorAll('video').forEach(v=>v.pause());});
for(const id of ['review-candidate','review-verdict','review-human','review-notes','review-score'])$(id).addEventListener('input',()=>{reviewState.formRevision++;$('review-confirmed').checked=false;$('promotion-confirmed').checked=false;});
window.addEventListener('beforeunload',event=>{if(reviewState.dirty){event.preventDefault();event.returnValue='';}});
window.ManjuReview={state:reviewState,normalizeReview,newReview,latestReview,sameCreativeIntent,promotionProof,report:reviewReport};
