'use strict';
(() => {
const $ = id => document.getElementById(id);
const ROLE_NAMES = {first_frame:'首帧',last_frame:'尾帧',subject_reference:'主体参考图',reference_video:'参考视频',reference_audio:'参考音频',source_video:'待编辑 / 延展视频',performance_video:'表演参考视频'};
const TASK_NAMES = {create:'从零创建',animate:'静帧动画',bridge:'首尾帧桥接',reference:'参考生成',edit:'修改视频',extend:'延展视频',perform:'表演参考'};
const ENTRIES={api_documented_not_connected:'API 文档档 · 未接通',web_app_only:'网页专用 · 无 Apps API',product_workflow:'产品工作流 · 非执行接口'};
const IMAGE_EXTS=['.png','.jpg','.jpeg','.webp','.heic','.heif'];
const VIDEO_EXTS=['.mp4','.mov','.webm','.mkv'];
const AUDIO_EXTS=['.wav','.mp3','.m4a','.aac','.flac'];
const REQUEST_KEYS=['schema_id','shot_id','task','prompt','duration_s','resolution','aspect_ratio','assets','preserve','change','stage','approved_draft_sha256'];
const ASSET_KEYS=['id','role','path','sha256','bytes','duration_ms','origin_model'];
const PROFILE_KEYS=['id','label','vendor','model_id','entry','status','claim_id','source_url','checked_on','review_after','modes','notes'];
const MODE_KEYS=['id','task','roles','min_total_assets','durations','duration_range','resolutions','aspect_ratios','high_resolution_requires_s','high_resolutions','input_duration_max_ms','input_duration_min_ms','input_total_duration_max_ms','input_bytes_max','input_extensions','required_origin_model','last_frame_max_source_ms','notes'];
const encoder=new TextEncoder(), MAX_FILE=128*1024*1024,MAX_TOTAL=512*1024*1024,STORE='manju.model-workbench.draft.v1';
const identifier=/^[A-Za-z0-9][A-Za-z0-9_.-]{0,79}$/,hashPattern=/^[a-f0-9]{64}$/;
let catalog=JSON.parse($('builtin-catalog').textContent);
const state={assets:[],files:new Map(),selected:null,plan:null,revision:0,dirty:false,busy:false,generation:0,stage:'draft',draftHash:null,sourceContext:null};
function element(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=String(text);if(cls)e.className=cls;return e;}
function status(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error);}
function require(condition,message){if(!condition)throw new Error(message);}
function onlyKeys(value,keys,label){require(value && typeof value==='object' && !Array.isArray(value),label+' 必须是对象');for(const key of Object.keys(value))require(keys.includes(key),label+' 包含未知字段：'+key);}
function string(value,max,label,min=0){require(typeof value==='string' && value.trim().length>=min && value.trim().length<=max,label+' 长度或类型不正确');return value.trim();}
function integer(value,min,max,label){require(Number.isSafeInteger(value)&&value>=min&&value<=max,label+' 必须是范围内的整数');return value;}
function nullableString(value,max,label){return value==null?null:string(value,max,label);}
function canonical(value){if(Array.isArray(value))return '['+value.map(canonical).join(',')+']';if(value && typeof value==='object')return '{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+canonical(value[k])).join(',')+'}';require(value!==undefined && !(typeof value==='number'&&!Number.isFinite(value)),'JSON 中存在无效值');return JSON.stringify(value);}
// Incremental SHA-256 keeps file hashing independent of secure-context APIs
// and bounds working memory to one chunk. Known-answer and Python parity tests
// cover padding boundaries, many chunks, non-ASCII text and a million bytes.
class SHA256 {
 constructor(){this.h=new Uint32Array([0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19]);this.buffer=new Uint8Array(64);this.used=0;this.total=0;this.finished=false;this.w=new Uint32Array(64);}
 static K=new Uint32Array([0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2]);
 block(bytes,offset=0){const w=this.w,rotr=(x,n)=>(x>>>n)|(x<<(32-n));for(let i=0;i<16;i++){const p=offset+4*i;w[i]=((bytes[p]<<24)|(bytes[p+1]<<16)|(bytes[p+2]<<8)|bytes[p+3])>>>0;}for(let i=16;i<64;i++){const a=w[i-15],b=w[i-2],s0=rotr(a,7)^rotr(a,18)^(a>>>3),s1=rotr(b,17)^rotr(b,19)^(b>>>10);w[i]=(w[i-16]+s0+w[i-7]+s1)>>>0;}let[a,b,c,d,e,f,g,h]=this.h;for(let i=0;i<64;i++){const s1=rotr(e,6)^rotr(e,11)^rotr(e,25),ch=(e&f)^(~e&g),t1=(h+s1+ch+SHA256.K[i]+w[i])>>>0,s0=rotr(a,2)^rotr(a,13)^rotr(a,22),maj=(a&b)^(a&c)^(b&c),t2=(s0+maj)>>>0;h=g;g=f;f=e;e=(d+t1)>>>0;d=c;c=b;b=a;a=(t1+t2)>>>0;}const out=[a,b,c,d,e,f,g,h];for(let i=0;i<8;i++)this.h[i]=(this.h[i]+out[i])>>>0;}
 update(data){require(!this.finished,'哈希已完成，不能继续写入');const bytes=data instanceof Uint8Array?data:new Uint8Array(data);this.total+=bytes.length;let offset=0;if(this.used){const count=Math.min(64-this.used,bytes.length);this.buffer.set(bytes.subarray(0,count),this.used);this.used+=count;offset=count;if(this.used===64){this.block(this.buffer);this.used=0;}}while(offset+64<=bytes.length){this.block(bytes,offset);offset+=64;}if(offset<bytes.length){this.buffer.set(bytes.subarray(offset),0);this.used=bytes.length-offset;}return this;}
 hex(){require(!this.finished,'哈希已完成');this.finished=true;this.buffer[this.used++]=0x80;if(this.used>56){this.buffer.fill(0,this.used);this.block(this.buffer);this.used=0;}this.buffer.fill(0,this.used,56);const v=new DataView(this.buffer.buffer);v.setUint32(56,Math.floor(this.total/0x20000000),false);v.setUint32(60,(this.total*8)>>>0,false);this.block(this.buffer);return Array.from(this.h,n=>n.toString(16).padStart(8,'0')).join('');}
}
async function hash(value){const raw=value instanceof ArrayBuffer?new Uint8Array(value):ArrayBuffer.isView(value)?new Uint8Array(value.buffer,value.byteOffset,value.byteLength):encoder.encode(canonical(value));if(globalThis.crypto?.subtle)return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',raw)),b=>b.toString(16).padStart(2,'0')).join('');return new SHA256().update(raw).hex();}
function casefold(s){return s.normalize('NFKC').toLowerCase().replaceAll('ß','ss').replaceAll('ς','σ');}
function safePath(name){require(typeof name==='string'&&name.length>0&&name.length<=240,'素材路径长度不正确');require(!name.startsWith('/')&&!/[\\\x00-\x1f:*?"<>|]/.test(name),'素材路径不安全');for(const p of name.split('/'))require(p && p!=='.' && p!=='..'&&!/[ .]$/.test(p)&&!/^(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])(?:\.|$)/i.test(p),'素材路径不是可移植文件名');return name;}
function extension(name){return (name.match(/\.[^./]+$/)?.[0]||'').toLowerCase();}
function normalizeAsset(a){onlyKeys(a,ASSET_KEYS,'素材');require(identifier.test(a.id),'素材 ID 不合法');require(Object.hasOwn(ROLE_NAMES,a.role),'素材用途不合法');const path=safePath(a.path);require(hashPattern.test(a.sha256),'素材 SHA-256 不正确');const allowed=['first_frame','last_frame','subject_reference'].includes(a.role)?IMAGE_EXTS:a.role==='reference_audio'?AUDIO_EXTS:VIDEO_EXTS;require(allowed.includes(extension(path)),'素材用途与文件扩展名不匹配');return {id:a.id,role:a.role,path,sha256:a.sha256,bytes:integer(a.bytes,1,2*1024*1024*1024,'素材字节数'),duration_ms:a.duration_ms==null?null:integer(a.duration_ms,1,86400000,'素材时长'),origin_model:nullableString(a.origin_model,120,'来源型号')};}
function normalizeRequest(r){onlyKeys(r,REQUEST_KEYS,'任务');require(!r.schema_id||r.schema_id==='manju.model-request/v1','未知任务版本');require(Object.hasOwn(TASK_NAMES,r.task),'未知任务类型');const request={schema_id:'manju.model-request/v1',shot_id:string(r.shot_id,120,'镜头编号',1),task:r.task,prompt:string(r.prompt,16000,'提示词',1),duration_s:r.duration_s==null?null:integer(r.duration_s,1,120,'目标时长'),resolution:nullableString(r.resolution,20,'分辨率'),aspect_ratio:nullableString(r.aspect_ratio,20,'画幅'),assets:r.assets||[],preserve:r.preserve||[],change:r.change||[],stage:r.stage||'draft',approved_draft_sha256:r.approved_draft_sha256||null};
 require(Array.isArray(request.assets)&&request.assets.length<=32,'素材数量不能超过 32');request.assets=request.assets.map(normalizeAsset);let ids=new Set(),paths=new Map();for(const a of request.assets){require(!ids.has(a.id),'素材 ID 重复');ids.add(a.id);const key=a.path.normalize('NFC').toLowerCase();if(paths.has(key))require(canonical(paths.get(key))===canonical([a.path,a.sha256,a.bytes]),'素材路径大小写冲突或哈希不一致');paths.set(key,[a.path,a.sha256,a.bytes]);}
 for(const key of ['preserve','change']){require(Array.isArray(request[key])&&request[key].length<=30,'约束最多 30 条');request[key]=request[key].map(s=>string(s,1000,'约束',1));}const preserved=new Set(request.preserve.map(casefold));require(!request.change.some(s=>preserved.has(casefold(s))),'同一内容不能同时要求保留和改变');require(request.task!=='edit'||(request.preserve.length&&request.change.length),'编辑任务需要填写保留项和改变项');require(['draft','final'].includes(request.stage),'未知制作阶段');require(!request.approved_draft_sha256||hashPattern.test(request.approved_draft_sha256),'草稿哈希不正确');require(request.stage!=='final'||request.approved_draft_sha256,'定稿必须引用已批准草稿');require(request.stage!=='draft'||!request.approved_draft_sha256,'草稿不能冒充定稿晋升');return request;}
function validDate(s){return typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&!Number.isNaN(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s;}
function normalizeCatalog(c){onlyKeys(c,['schema_id','revision','profiles'],'能力档');require(c.schema_id==='manju.model-catalog/v1','未知能力目录版本');string(c.revision,100,'目录修订',1);require(Array.isArray(c.profiles)&&c.profiles.length>0&&c.profiles.length<=100,'能力档数量不正确');const ids=new Set(),claims=new Set();
 for(const p of c.profiles){onlyKeys(p,PROFILE_KEYS,'型号档');require(identifier.test(p.id)&&identifier.test(p.claim_id),'型号或证据 ID 不正确');require(!ids.has(p.id)&&!claims.has(p.claim_id),'型号或证据 ID 重复');ids.add(p.id);claims.add(p.claim_id);require(p.status==='authoring_only'&&Object.hasOwn(ENTRIES,p.entry),'只允许离线作者档');string(p.label,140,'名称',1);string(p.vendor,80,'厂商',1);nullableString(p.model_id,120,'型号');let u;try{u=new URL(p.source_url);}catch{throw new Error('来源 URL 无效');}require(u.protocol==='https:'&&!u.username&&!u.password&&!u.search,'来源必须是无凭据的 HTTPS URL');require(validDate(p.checked_on)&&validDate(p.review_after)&&p.review_after>=p.checked_on,'核验日期不正确');require(Array.isArray(p.notes)&&p.notes.every(x=>typeof x==='string'),'档位备注必须是文本');require(Array.isArray(p.modes)&&p.modes.length>0&&p.modes.length<=20,'模式数量不正确');const modes=new Set();
 for(const m of p.modes){onlyKeys(m,MODE_KEYS,'模式');require(identifier.test(m.id)&&!modes.has(m.id)&&Object.hasOwn(TASK_NAMES,m.task),'模式 ID 或任务不正确');modes.add(m.id);onlyKeys(m.roles,Object.keys(ROLE_NAMES),'用途计数');let maximum=0;for(const pair of Object.values(m.roles)){require(Array.isArray(pair)&&pair.length===2,'素材计数不正确');integer(pair[0],0,32,'最少素材数');integer(pair[1],pair[0],32,'最多素材数');maximum+=pair[1];}integer(m.min_total_assets,0,Math.min(32,maximum),'总素材数');require(!(m.durations!==null&&m.duration_range!==null),'不能同时声明时长列表和范围');if(m.durations!==null){require(Array.isArray(m.durations),'时长应为数组');m.durations.forEach(d=>integer(d,1,120,'时长'));}if(m.duration_range!==null){require(Array.isArray(m.duration_range)&&m.duration_range.length===2,'时长范围不正确');integer(m.duration_range[0],1,120,'最短时长');integer(m.duration_range[1],m.duration_range[0],120,'最长时长');}for(const k of ['resolutions','aspect_ratios','high_resolutions','notes'])require((m[k]===null&&['resolutions','aspect_ratios'].includes(k))||(Array.isArray(m[k])&&m[k].every(v=>typeof v==='string')),k+' 应为文本数组');for(const k of ['input_duration_max_ms','input_duration_min_ms','input_total_duration_max_ms','input_bytes_max']){onlyKeys(m[k],Object.keys(ROLE_NAMES),k);Object.values(m[k]).forEach(n=>integer(n,1,2147483648,k));}onlyKeys(m.input_extensions,Object.keys(ROLE_NAMES),'媒体扩展名');for(const exts of Object.values(m.input_extensions))require(Array.isArray(exts)&&exts.every(e=>typeof e==='string'&&/^\.[a-z0-9]+$/.test(e)),'扩展名列表无效');}}
 return c;}
function modeReport(r,p,m,today){const errors=[],warnings=[...p.notes,...m.notes];let counts={};for(const a of r.assets)counts[a.role]=(counts[a.role]||0)+1;
 if(r.task!==m.task)errors.push('task_not_supported_by_mode');for(const role of new Set([...Object.keys(counts),...Object.keys(m.roles)])){const [lo,hi]=m.roles[role]||[0,0];if(!((counts[role]||0)>=lo&&(counts[role]||0)<=hi))errors.push(`role_count:${role}:expected_${lo}_to_${hi}`);}if(r.assets.length<m.min_total_assets)errors.push('at_least_one_conditioning_asset_required');
 if(r.duration_s!==null){if(m.durations!==null&&!m.durations.includes(r.duration_s))errors.push('duration_not_supported');else if(m.duration_range && !(m.duration_range[0]<=r.duration_s&&r.duration_s<=m.duration_range[1]))errors.push('duration_out_of_range');else if(m.durations===null&&m.duration_range===null)warnings.push('duration_limit_not_verified:confirm_with_vendor');}else warnings.push('duration_unspecified:confirm_with_vendor');
 for(const [key,allowed] of [['resolution',m.resolutions],['aspect_ratio',m.aspect_ratios]]){if(r[key]===null)warnings.push(key+'_unspecified:confirm_with_vendor');else if(allowed===null)warnings.push(key+'_limit_not_verified:confirm_with_vendor');else if(!allowed.includes(r[key]))errors.push(key+'_not_supported');}if(m.high_resolutions.includes(r.resolution)&&r.duration_s!==m.high_resolution_requires_s)errors.push('high_resolution_requires_'+m.high_resolution_requires_s+'_seconds');
 for(const a of r.assets){if(m.input_bytes_max[a.role]&&a.bytes>m.input_bytes_max[a.role])errors.push('asset_bytes_exceeded:'+a.id);if(m.input_extensions[a.role]&&!m.input_extensions[a.role].includes(extension(a.path)))errors.push('asset_extension_not_supported:'+a.id);if(m.input_duration_max_ms[a.role]||m.input_duration_min_ms[a.role]){if(a.duration_ms===null)errors.push('asset_duration_required:'+a.id);else if(a.duration_ms>(m.input_duration_max_ms[a.role]||86400000)||a.duration_ms<(m.input_duration_min_ms[a.role]||1))errors.push('asset_duration_out_of_range:'+a.id);}if(a.role==='source_video'&&m.required_origin_model&&a.origin_model!==m.required_origin_model)errors.push('source_video_origin_must_be:'+m.required_origin_model);}
 for(const [role,limit]of Object.entries(m.input_total_duration_max_ms))if(r.assets.filter(a=>a.role===role).reduce((n,a)=>n+(a.duration_ms||0),0)>limit)errors.push('total_asset_duration_exceeded:'+role);
 if(m.last_frame_max_source_ms&&counts.last_frame&&r.assets.some(a=>a.role==='source_video'&&(a.duration_ms===null||a.duration_ms>m.last_frame_max_source_ms)))errors.push('last_frame_is_not_clip_end_for_this_input_length');if(p.checked_on>today)errors.push('evidence_date_in_future');if(today>p.review_after)warnings.push('evidence_review_overdue:reverify_before_external_submission');warnings.push('authoring_only:no_API_call_no_quality_or_price_guarantee');return {profile_id:p.id,mode_id:m.id,compatible:errors.length===0,errors:[...new Set(errors)].sort(),warnings:[...new Set(warnings)].sort()};}
function options(r,c=catalog,today=new Date().toISOString().slice(0,10)){return c.profiles.flatMap(p=>p.modes.filter(m=>m.task===r.task).map(m=>modeReport(r,p,m,today)));}
function getRequest(){return normalizeRequest({schema_id:'manju.model-request/v1',shot_id:$('shot-id').value,task:$('task').value,prompt:$('prompt').value,duration_s:$('duration').value===''?null:Number($('duration').value),resolution:$('resolution').value||null,aspect_ratio:$('ratio').value||null,assets:state.assets,preserve:$('preserve').value.split('\n').map(s=>s.trim()).filter(Boolean),change:$('change').value.split('\n').map(s=>s.trim()).filter(Boolean),stage:state.stage,approved_draft_sha256:state.draftHash});}
function chooseValue(id,value){const field=$(id);if(field.tagName==='SELECT'&&value&&!Array.from(field.options).some(o=>o.value===value)){const op=element('option',value);op.value=value;field.append(op);}field.value=value??'';}
function fillRequest(r){for(const [id,key]of [['shot-id','shot_id'],['task','task'],['prompt','prompt'],['duration','duration_s'],['resolution','resolution'],['ratio','aspect_ratio']])chooseValue(id,r[key]);$('preserve').value=r.preserve.join('\n');$('change').value=r.change.join('\n');state.assets=r.assets;state.stage=r.stage;state.draftHash=r.approved_draft_sha256;renderAssets();$('stage-status').textContent=state.stage==='final'?'当前阶段：定稿，绑定草稿 '+state.draftHash:'当前阶段：草稿。定稿晋升需要先批准实际草稿文件。';}
function rawDraft(){return {version:1,form:Object.fromEntries(['shot-id','task','prompt','duration','resolution','ratio','preserve','change','reviewer'].map(id=>[id,$(id).value])),assets:state.assets,stage:state.stage,draftHash:state.draftHash,sourceContext:state.sourceContext};}
function persist(){try{localStorage.setItem(STORE,JSON.stringify(rawDraft()));$('storage-note').textContent='草稿已在当前浏览器临时保存；媒体不在本地存储中。请导出文件备份。';}catch{$('storage-note').textContent='浏览器不允许保存草稿。关闭前务必导出任务 JSON 或 ZIP。';}}
function invalidate(){state.revision++;state.selected=null;state.plan=null;state.dirty=true;$('human-confirmed').checked=false;$('ack-warnings').checked=false;$('options').replaceChildren(element('div','任务已变化，请重新检查适配。','empty'));$('plan-summary').textContent='';persist();}
function message(code){const exact={task_not_supported_by_mode:'模式不支持这个任务',duration_not_supported:'目标时长不在支持列表中',duration_out_of_range:'目标时长超出已核验范围',resolution_not_supported:'分辨率不受此模式支持',aspect_ratio_not_supported:'目标画幅不受支持，或该输入模式只跟随素材画幅',at_least_one_conditioning_asset_required:'需要至少一个参考素材',evidence_date_in_future:'能力档的核验日期在未来，不能采用',last_frame_is_not_clip_end_for_this_input_length:'该输入长度下，供应商的尾帧卡并非整段最后一帧', 'authoring_only:no_API_call_no_quality_or_price_guarantee':'仅作创作交接：没有 API 执行、画质或价格保证','evidence_review_overdue:reverify_before_external_submission':'能力证据已到复核期限，提交前必须重新核验'};if(exact[code])return exact[code];if(code.startsWith('role_count:')){const parts=code.split(':');return (ROLE_NAMES[parts[1]]||parts[1])+' 数量不符：'+parts[2].replace('expected_','需要 ').replace('_to_',' 至 ');}const prefix={asset_bytes_exceeded:'素材文件超过限制',asset_duration_required:'需要补充素材时长（毫秒）',asset_duration_out_of_range:'素材时长不合要求',total_asset_duration_exceeded:'参考素材总时长超限',asset_extension_not_supported:'供应商不支持此素材格式',source_video_origin_must_be:'源视频必须声明为该模型的先前生成结果'};for(const[k,v]of Object.entries(prefix))if(code.startsWith(k+':'))return v+'：'+code.slice(k.length+1);if(code.includes('high_resolution_requires_'))return '此高分辨率要求 '+code.split('_')[3]+' 秒';if(code.includes('_unspecified'))return '参数未指定：'+code.split('_unspecified')[0]+'，提交前确认';if(code.includes('_limit_not_verified'))return '参数限制尚未核验：'+code.split('_limit_not_verified')[0]+'，不能当作支持保证';return code;}
async function renderPlan(){const r=getRequest(),revision=state.revision,day=new Date().toISOString().slice(0,10);const rows=options(r,catalog,day);const report={schema_id:'manju.model-plan/v1',request_sha256:await hash(r),catalog_sha256:await hash(catalog),evaluated_on:day,selected_profile:null,ranked_by_quality:false,options:rows};if(revision!==state.revision)return null;state.plan=report;state.selected=null;$('options').replaceChildren();$('plan-summary').textContent=`${rows.filter(o=>o.compatible).length} 个模式无已知冲突 / ${rows.length} 个已核验模式。目录：${catalog.revision}`;
 for(const o of rows){const p=catalog.profiles.find(p=>p.id===o.profile_id),card=element('div',undefined,'option'+(o.compatible?'':' blocked'));const top=element('div',undefined,'option-head'),label=element('label'),radio=document.createElement('input');radio.type='radio';radio.name='model-choice';radio.value=p.id+'/'+o.mode_id;radio.disabled=!o.compatible;radio.setAttribute('aria-label',p.label+' '+o.mode_id);radio.addEventListener('change',()=>{state.selected={profile_id:p.id,mode_id:o.mode_id};$('human-confirmed').checked=false;$('ack-warnings').checked=false;document.querySelectorAll('.option').forEach(e=>e.classList.remove('selected'));card.classList.add('selected');});label.append(radio,document.createTextNode(p.label+' · '+o.mode_id));top.append(label,element('span',o.compatible?'无已知冲突':'已阻断','tag '+(o.compatible?'good':'bad')));card.append(top,element('span',ENTRIES[p.entry],'tag'));for(const e of o.errors)card.append(element('div',message(e),'reason'));const details=element('details'),summary=element('summary',`告警与证据（${o.warnings.length}）`);details.append(summary);for(const w of o.warnings)details.append(element('div',message(w),'notice'));details.append(element('div',`核验 ${p.checked_on} · 复核期限 ${p.review_after}`,'small'),element('div',p.source_url,'small muted'));card.append(details);$('options').append(card);}
 if(rows.length===0)$('options').append(element('div','尚无经过核验的任务档。保留任务草稿，不会自动退回别的任务或虚构接口。','empty'));status('检查完成。选择一个无已知冲突的模式，展开阅读告警，再确认交接。');return report;}
function renderAssets(){$('assets').replaceChildren();if(!state.assets.length){$('assets').append(element('div','没有素材。从零创建可以不添加文件。','empty'));return;}for(const a of state.assets){const row=element('div',undefined,'asset'),top=element('div',undefined,'asset-head'),info=element('div');const file=state.files.get(a.sha256)?.file;info.append(element('strong',file?.name||a.path),element('code',a.sha256),element('div',(file?'已绑定本地文件':'仅有记录，请重新选择文件')+` · ${(a.bytes/1048576).toFixed(2)} MiB`,file?'bound':'unbound'));const remove=element('button','移除');remove.addEventListener('click',()=>{state.assets=state.assets.filter(x=>x.id!==a.id);if(!state.assets.some(x=>x.sha256===a.sha256))state.files.delete(a.sha256);invalidate();renderAssets();});const reuse=element('button','按上方用途复用');reuse.addEventListener('click',handled(()=>{const role=$('asset-role').value;require(!state.assets.some(x=>x.sha256===a.sha256&&x.role===role),'该文件已经绑定这个用途');require(state.assets.length<32,'最多绑定 32 个素材角色');let n=1;while(state.assets.some(x=>x.id==='A'+n))n++;state.assets.push(normalizeAsset({...a,id:'A'+n,role}));invalidate();renderAssets();}));const buttons=element('div');buttons.append(reuse,remove);top.append(info,buttons);row.append(top);const controls=element('div',undefined,'formrow'),label=element('label','素材用途','field'),select=element('select');for(const[k,v]of Object.entries(ROLE_NAMES)){const op=element('option',v);op.value=k;select.append(op);}select.value=a.role;select.addEventListener('change',()=>{a.role=select.value;invalidate();renderAssets();});label.append(select);controls.append(label);if(VIDEO_EXTS.includes(extension(a.path))||AUDIO_EXTS.includes(extension(a.path))){const duration=element('label','素材时长（毫秒，声明）','field'),input=document.createElement('input');input.type='number';input.min='1';input.max='86400000';input.value=a.duration_ms||'';input.addEventListener('input',()=>{a.duration_ms=input.value===''?null:Number(input.value);invalidate();});duration.append(input);controls.append(duration);}if(a.role==='source_video'){const origin=element('label','来源型号声明（Veo 延展填写 veo-3.1）','field'),input=document.createElement('input');input.value=a.origin_model||'';input.maxLength=120;input.addEventListener('input',()=>{a.origin_model=input.value.trim()||null;invalidate();});origin.append(input);controls.append(origin);}row.append(controls);$('assets').append(row);}}
const CRC_TABLE=(()=>{const t=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=c&1?0xedb88320^(c>>>1):c>>>1;t[n]=c>>>0;}return t;})();
function crc32(data){let crc=0xffffffff;for(const x of data)crc=CRC_TABLE[(crc^x)&255]^(crc>>>8);return (crc^0xffffffff)>>>0;}
async function inspectFile(file){require(file.size>0&&file.size<=MAX_FILE,'浏览器只读取 1 字节至 128 MiB 的单个文件；较大素材请用 Python 命令行交接');const sha=new SHA256();let crc=0xffffffff;for(let start=0;start<file.size;start+=1048576){const bytes=new Uint8Array(await file.slice(start,start+1048576).arrayBuffer());sha.update(bytes);for(const x of bytes)crc=CRC_TABLE[(crc^x)&255]^(crc>>>8);}return {file,sha256:sha.hex(),crc:(crc^0xffffffff)>>>0};}
async function mediaDuration(file){if(!VIDEO_EXTS.includes(extension(file.name))&&!AUDIO_EXTS.includes(extension(file.name)))return null;return new Promise(resolve=>{const media=document.createElement('video'),url=URL.createObjectURL(file);let done=false;const finish=value=>{if(done)return;done=true;clearTimeout(timer);media.removeAttribute('src');media.load();URL.revokeObjectURL(url);resolve(value);};const timer=setTimeout(()=>finish(null),5000);media.preload='metadata';media.onloadedmetadata=()=>finish(Number.isFinite(media.duration)&&media.duration>0?Math.round(media.duration*1000):null);media.onerror=()=>finish(null);media.src=url;});}
async function addFiles(files){require(!state.busy,'正在处理文件，请完成当前操作后重试');state.busy=true;const generation=state.generation,requestedRole=$('asset-role').value;try{for(const file of files){status('正在本地读取并计算哈希：'+file.name);const entry=await inspectFile(file);if(generation!==state.generation)return;let total=[...state.files.values()].reduce((n,e)=>n+e.file.size,0)+(state.files.has(entry.sha256)?0:file.size);require(total<=MAX_TOTAL,'本页面绑定媒体总计不得超过 512 MiB；请分批创建交接包');state.files.set(entry.sha256,entry);const existing=state.assets.filter(a=>a.sha256===entry.sha256&&a.bytes===file.size);if(!existing.length){let n=1;while(state.assets.some(a=>a.id==='A'+n))n++;const duration_ms=await mediaDuration(file);if(generation!==state.generation)return;const a=normalizeAsset({id:'A'+n,role:requestedRole,path:'asset-'+entry.sha256.slice(0,16)+extension(file.name),sha256:entry.sha256,bytes:file.size,duration_ms,origin_model:null});require(state.assets.length<32,'最多绑定 32 个素材角色');state.assets.push(a);}invalidate();renderAssets();}status('文件已经在本机绑定。请核对用途和时长，再检查适配。');}finally{state.busy=false;$('asset-files').value='';}}
function jsonBytes(value){return encoder.encode(JSON.stringify(value,null,2)+'\n');}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function zipStore(entries){require(entries.length<65535,'ZIP 条目过多');const parts=[],central=[];let offset=0;for(const entry of entries){safePath(entry.name);const name=encoder.encode(entry.name),size=entry.data.size??entry.data.byteLength;require(size<=0xffffffff&&offset+size<0xffffffff,'超出 ZIP32 大小限制');const header=new Uint8Array(30+name.length),v=new DataView(header.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint16(12,33,true);v.setUint32(14,entry.crc,true);v.setUint32(18,size,true);v.setUint32(22,size,true);v.setUint16(26,name.length,true);header.set(name,30);parts.push(header,entry.data);const c=new Uint8Array(46+name.length),d=new DataView(c.buffer);d.setUint32(0,0x02014b50,true);d.setUint16(4,20,true);d.setUint16(6,20,true);d.setUint16(8,0x800,true);d.setUint16(14,33,true);d.setUint32(16,entry.crc,true);d.setUint32(20,size,true);d.setUint32(24,size,true);d.setUint16(28,name.length,true);d.setUint32(42,offset,true);c.set(name,46);central.push(c);offset+=header.length+size;}const centralSize=central.reduce((n,c)=>n+c.length,0),end=new Uint8Array(22),v=new DataView(end.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(8,entries.length,true);v.setUint16(10,entries.length,true);v.setUint32(12,centralSize,true);v.setUint32(16,offset,true);return new Blob([...parts,...central,end],{type:'application/zip'});}
function brief(r,p,m){let rows=['# Manju 模型交接说明','',`镜头：${r.shot_id}`,`创作任务：${r.task} / ${r.stage}`,`作者适配档：${p.label} / ${m.id}`,`使用入口：${p.entry}；本项目未连接此商业服务。`,'','## 提示词','',r.prompt,'','## 保留项',...r.preserve.map(s=>'- '+s),'','## 改变项',...r.change.map(s=>'- '+s),'','## 目标参数',`时长：${r.duration_s===null?'None':r.duration_s} 秒；分辨率：${r.resolution===null?'None':r.resolution}；画幅：${r.aspect_ratio===null?'None':r.aspect_ratio}`,'','## 素材绑定',...r.assets.map(a=>`- ${a.id} | ${a.role} | assets/${a.path} | SHA-256 ${a.sha256}`)];if(r.approved_draft_sha256)rows.push('',`已批准草稿内容：${r.approved_draft_sha256}`);rows.push('','## 能力证据',p.source_url,`核验：${p.checked_on}；复核期限：${p.review_after}；声明：${p.claim_id}`,'','未知、账户、地区、价格、可用性和媒体编码限制仍需提交前核验。','人工批准只固定这份创作交接，不授权付费、不自动选片、不批准 Picture Lock。','');return rows.join('\n');}
async function exportBundle(){
 require(!state.busy,'文件仍在处理中');
 const request=getRequest(),selected=state.selected,revision=state.revision;
 require(selected&&state.plan,'先检查适配并明确选择一个模式');
 require($('human-confirmed').checked&&$('ack-warnings').checked,'请先明确确认创作交接并阅读告警');
 const reviewer=string($('reviewer').value,120,'确认人',1),now=new Date(),day=now.toISOString().slice(0,10);
 const option=options(request,catalog,day).find(o=>o.profile_id===selected.profile_id&&o.mode_id===selected.mode_id);
 require(option?.compatible,'当前任务和模式不再兼容，请重新检查');
 for(const a of request.assets)require(state.files.has(a.sha256),'缺少实际素材文件：'+a.path);
 state.busy=true;$('export-bundle').disabled=true;
 try{
  let proof=null;
  if(request.stage==='final'){
   require(window.ManjuReview,'本版本没有审片证据检查器，拒绝仅靠哈希声明导出定稿');
   proof=await window.ManjuReview.promotionProof(request);
  }
  const approval={schema_id:'manju.model-approval/v1',request_sha256:await hash(request),catalog_sha256:await hash(catalog),profile_id:selected.profile_id,mode_id:selected.mode_id,reviewer,declared_at:now.toISOString(),acknowledged_warnings:option.warnings,human_declared:true,external_execution_authorized:false};
  const profile=catalog.profiles.find(p=>p.id===selected.profile_id),mode=profile.modes.find(m=>m.id===selected.mode_id);
  let entries=[],manifest={schema_id:proof?'manju.model-bundle/v2':'manju.model-bundle/v1',files:{}};
  for(const [name,data]of [['REQUEST.json',jsonBytes(request)],['CATALOG.json',jsonBytes(catalog)],['APPROVAL.json',jsonBytes(approval)],['BRIEF.md',encoder.encode(brief(request,profile,mode))]]){
   entries.push({name,data,crc:crc32(data)});manifest.files[name]=await hash(data);
  }
  const names=new Set();
  for(const a of request.assets){
   const name='assets/'+a.path;if(names.has(name))continue;names.add(name);
   status('正在重新校验并封装：'+a.path);
   const entry=await inspectFile(state.files.get(a.sha256).file);
   require(entry.sha256===a.sha256&&entry.file.size===a.bytes,'素材内容变化，拒绝使用旧审批');
   entries.push({name,data:entry.file,crc:entry.crc});manifest.files[name]=a.sha256;
  }
  if(proof){
   const data=jsonBytes(proof.document),name='DRAFT_REVIEW.json';require(data.length<=2*1024*1024,'审片记录过大');
   entries.push({name,data,crc:crc32(data)});manifest.files[name]=await hash(data);
   const draft='approved-draft/'+proof.candidate.sha256+extension(proof.candidate.filename);
   entries.push({name:draft,data:proof.entry.file,crc:proof.entry.crc});manifest.files[draft]=proof.candidate.sha256;
   require(proof.revision===window.ManjuReview.state.revision,'审片记录在封包期间改变，未导出旧决定');
  }
  require(entries.reduce((n,e)=>n+(e.data.size??e.data.byteLength),0)<=MAX_TOTAL,'封包超过浏览器本地 512 MiB 限制');
  require(revision===state.revision,'任务在封包期间发生变化，未导出旧审批');
  const data=jsonBytes(manifest);entries.push({name:'MANIFEST.json',data,crc:crc32(data)});
  download(zipStore(entries),'MANJU_HANDOFF_'+approval.request_sha256.slice(0,12)+'.zip');
  state.dirty=false;status('已触发素材包下载。请在浏览器下载列表确认并保存；本页面无法替你确认磁盘保存是否成功。');
 }finally{state.busy=false;$('export-bundle').disabled=false;}
}
async function parseFile(file){require(file&&file.size<=2*1024*1024,'JSON 最大 2 MiB');return JSON.parse(await file.text());}
async function importRequest(file){let value=await parseFile(file),context=null;if(value.schema_id==='manju.project-authoring-import/v1'){require(await hash(value.source_plan)===value.source_plan_sha256,'原项目上下文哈希不符');context={source_plan:value.source_plan,source_plan_sha256:value.source_plan_sha256,warnings:value.warnings||[]};value=value.request;}const request=normalizeRequest(value);state.generation++;state.files=new Map([...state.files].filter(([h])=>request.assets.some(a=>a.sha256===h)));state.sourceContext=context;fillRequest(request);showContext();invalidate();status('已导入任务。媒体字节未写入草稿，请重新选择本地文件绑定；原工程没有被修改。');}
function showContext(){$('source-details').hidden=!state.sourceContext;$('source-context').textContent=state.sourceContext?JSON.stringify(state.sourceContext,null,2):'';}
function handled(fn){return async(...args)=>{try{await fn(...args);}catch(e){status(e.message||String(e),true);}};}
for(const id of ['shot-id','task','prompt','duration','resolution','ratio','preserve','change'])$(id).addEventListener('input',invalidate);
$('reviewer').addEventListener('input',()=>{$('human-confirmed').checked=false;persist();});
$('check-plan').addEventListener('click',handled(renderPlan));$('asset-files').addEventListener('change',handled(e=>addFiles([...e.target.files])));
$('export-request').addEventListener('click',handled(async()=>{const r=getRequest();download(new Blob([jsonBytes(r)],{type:'application/json'}),'MANJU_REQUEST_'+(await hash(r)).slice(0,12)+'.json');state.dirty=false;status('已触发任务 JSON 下载。此文件不包含媒体，请自行确认下载列表。');}));
$('export-bundle').addEventListener('click',handled(exportBundle));$('export-catalog').addEventListener('click',()=>download(new Blob([jsonBytes(catalog)],{type:'application/json'}),'MANJU_CATALOG.json'));
$('import-request').addEventListener('change',handled(async e=>{await importRequest(e.target.files[0]);e.target.value='';}));
$('import-catalog').addEventListener('change',handled(async e=>{catalog=normalizeCatalog(await parseFile(e.target.files[0]));invalidate();status('已加载用户提供的能力档。来源网页没有被自动访问；请自行核验其真实性和时效。');e.target.value='';}));
$('reset').addEventListener('click',()=>{if(!confirm('清空当前页面的任务草稿？已经导出的文件不会被删除。'))return;state.generation++;state.files.clear();state.sourceContext=null;fillRequest({shot_id:'镜头01',task:'create',prompt:'',duration_s:8,resolution:'720p',aspect_ratio:'16:9',assets:[],preserve:[],change:[],stage:'draft',approved_draft_sha256:null});$('reviewer').value='';showContext();invalidate();state.dirty=false;try{localStorage.removeItem(STORE);}catch{}status('已清空当前任务。磁盘中的原素材和导出文件没有改变。');});
window.addEventListener('beforeunload',e=>{if(state.dirty){e.preventDefault();e.returnValue='';}});
chooseValue('resolution','720p');chooseValue('ratio','16:9');
try{const saved=localStorage.getItem(STORE);if(saved&&saved.length<=2*1024*1024){const draft=JSON.parse(saved);require(draft.version===1&&draft.form,'不支持的草稿');for(const[id,v]of Object.entries(draft.form)){require(['shot-id','task','prompt','duration','resolution','ratio','preserve','change','reviewer'].includes(id)&&typeof v==='string'&&v.length<=30000,'草稿字段无效');chooseValue(id,v);}require(Array.isArray(draft.assets)&&draft.assets.length<=32,'草稿素材无效');state.assets=draft.assets.map(normalizeAsset);state.stage=draft.stage==='final'?'final':'draft';state.draftHash=hashPattern.test(draft.draftHash||'')?draft.draftHash:null;state.sourceContext=draft.sourceContext||null;showContext();renderAssets();status('已恢复浏览器中的任务草稿。没有恢复媒体字节，请重新绑定原文件。');}}catch{$('storage-note').textContent='未恢复旧草稿。请使用已经导出的 JSON；当前页面仍可正常工作。';}
// The same pure functions are exposed for cross-language parity tests; no remote hook.
window.ManjuWorkbench={SHA256,normalizeRequest,normalizeCatalog,modeReport,options,canonical,hash,crc32,zipStore,brief,getRequest,state,roleNames:ROLE_NAMES,element,status,handled,inspectFile,download,jsonBytes,fillRequest,invalidate,persist,renderAssets,importRequest,catalog:()=>catalog};
// REVIEW_SCRIPT
// WORKSPACE_SCRIPT
})();
